// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play_browse.proto

package libreplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BrowseResponse struct {
	ContentsUrl               *string       `protobuf:"bytes,1,opt,name=contentsUrl" json:"contentsUrl,omitempty"`
	PromoUrl                  *string       `protobuf:"bytes,2,opt,name=promoUrl" json:"promoUrl,omitempty"`
	Category                  []*BrowseLink `protobuf:"bytes,3,rep,name=category" json:"category,omitempty"`
	Breadcrumb                []*BrowseLink `protobuf:"bytes,4,rep,name=breadcrumb" json:"breadcrumb,omitempty"`
	QuickLink                 []*QuickLink  `protobuf:"bytes,5,rep,name=quickLink" json:"quickLink,omitempty"`
	ServerLogsCookie          []byte        `protobuf:"bytes,6,opt,name=serverLogsCookie" json:"serverLogsCookie,omitempty"`
	Title                     *string       `protobuf:"bytes,7,opt,name=title" json:"title,omitempty"`
	BackendId                 *int32        `protobuf:"varint,8,opt,name=backendId" json:"backendId,omitempty"`
	BrowseTab                 []*BrowseTab  `protobuf:"bytes,9,rep,name=browseTab" json:"browseTab,omitempty"`
	LandingTabIndex           *int32        `protobuf:"varint,10,opt,name=landingTabIndex" json:"landingTabIndex,omitempty"`
	QuickLinkTabIndex         *int32        `protobuf:"varint,11,opt,name=quickLinkTabIndex" json:"quickLinkTabIndex,omitempty"`
	QuickLinkFallbackTabIndex *int32        `protobuf:"varint,12,opt,name=quickLinkFallbackTabIndex" json:"quickLinkFallbackTabIndex,omitempty"`
	IsFamilySafe              *bool         `protobuf:"varint,14,opt,name=isFamilySafe" json:"isFamilySafe,omitempty"`
	TabStyle                  *int32        `protobuf:"varint,15,opt,name=tabStyle" json:"tabStyle,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}      `json:"-"`
	XXX_unrecognized          []byte        `json:"-"`
	XXX_sizecache             int32         `json:"-"`
}

func (m *BrowseResponse) Reset()         { *m = BrowseResponse{} }
func (m *BrowseResponse) String() string { return proto.CompactTextString(m) }
func (*BrowseResponse) ProtoMessage()    {}
func (*BrowseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf455f9497dac02, []int{0}
}

func (m *BrowseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseResponse.Unmarshal(m, b)
}
func (m *BrowseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseResponse.Marshal(b, m, deterministic)
}
func (m *BrowseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseResponse.Merge(m, src)
}
func (m *BrowseResponse) XXX_Size() int {
	return xxx_messageInfo_BrowseResponse.Size(m)
}
func (m *BrowseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseResponse proto.InternalMessageInfo

func (m *BrowseResponse) GetContentsUrl() string {
	if m != nil && m.ContentsUrl != nil {
		return *m.ContentsUrl
	}
	return ""
}

func (m *BrowseResponse) GetPromoUrl() string {
	if m != nil && m.PromoUrl != nil {
		return *m.PromoUrl
	}
	return ""
}

func (m *BrowseResponse) GetCategory() []*BrowseLink {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *BrowseResponse) GetBreadcrumb() []*BrowseLink {
	if m != nil {
		return m.Breadcrumb
	}
	return nil
}

func (m *BrowseResponse) GetQuickLink() []*QuickLink {
	if m != nil {
		return m.QuickLink
	}
	return nil
}

func (m *BrowseResponse) GetServerLogsCookie() []byte {
	if m != nil {
		return m.ServerLogsCookie
	}
	return nil
}

func (m *BrowseResponse) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *BrowseResponse) GetBackendId() int32 {
	if m != nil && m.BackendId != nil {
		return *m.BackendId
	}
	return 0
}

func (m *BrowseResponse) GetBrowseTab() []*BrowseTab {
	if m != nil {
		return m.BrowseTab
	}
	return nil
}

func (m *BrowseResponse) GetLandingTabIndex() int32 {
	if m != nil && m.LandingTabIndex != nil {
		return *m.LandingTabIndex
	}
	return 0
}

func (m *BrowseResponse) GetQuickLinkTabIndex() int32 {
	if m != nil && m.QuickLinkTabIndex != nil {
		return *m.QuickLinkTabIndex
	}
	return 0
}

func (m *BrowseResponse) GetQuickLinkFallbackTabIndex() int32 {
	if m != nil && m.QuickLinkFallbackTabIndex != nil {
		return *m.QuickLinkFallbackTabIndex
	}
	return 0
}

func (m *BrowseResponse) GetIsFamilySafe() bool {
	if m != nil && m.IsFamilySafe != nil {
		return *m.IsFamilySafe
	}
	return false
}

func (m *BrowseResponse) GetTabStyle() int32 {
	if m != nil && m.TabStyle != nil {
		return *m.TabStyle
	}
	return 0
}

type BrowseTab struct {
	Title                  *string       `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	ServerLogsCookie       []byte        `protobuf:"bytes,2,opt,name=serverLogsCookie" json:"serverLogsCookie,omitempty"`
	ListUrl                *string       `protobuf:"bytes,3,opt,name=listUrl" json:"listUrl,omitempty"`
	Category               []*BrowseLink `protobuf:"bytes,4,rep,name=category" json:"category,omitempty"`
	QuickLink              []*QuickLink  `protobuf:"bytes,5,rep,name=quickLink" json:"quickLink,omitempty"`
	QuickLinkTitle         *string       `protobuf:"bytes,6,opt,name=quickLinkTitle" json:"quickLinkTitle,omitempty"`
	CategoriesTitle        *string       `protobuf:"bytes,7,opt,name=categoriesTitle" json:"categoriesTitle,omitempty"`
	BackendId              *int32        `protobuf:"varint,8,opt,name=backendId" json:"backendId,omitempty"`
	HighlightsBannerUrl    *string       `protobuf:"bytes,9,opt,name=highlightsBannerUrl" json:"highlightsBannerUrl,omitempty"`
	EntertainmentTabBubble *TabBubble    `protobuf:"bytes,10,opt,name=entertainmentTabBubble" json:"entertainmentTabBubble,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}      `json:"-"`
	XXX_unrecognized       []byte        `json:"-"`
	XXX_sizecache          int32         `json:"-"`
}

func (m *BrowseTab) Reset()         { *m = BrowseTab{} }
func (m *BrowseTab) String() string { return proto.CompactTextString(m) }
func (*BrowseTab) ProtoMessage()    {}
func (*BrowseTab) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf455f9497dac02, []int{1}
}

func (m *BrowseTab) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseTab.Unmarshal(m, b)
}
func (m *BrowseTab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseTab.Marshal(b, m, deterministic)
}
func (m *BrowseTab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseTab.Merge(m, src)
}
func (m *BrowseTab) XXX_Size() int {
	return xxx_messageInfo_BrowseTab.Size(m)
}
func (m *BrowseTab) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseTab.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseTab proto.InternalMessageInfo

func (m *BrowseTab) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *BrowseTab) GetServerLogsCookie() []byte {
	if m != nil {
		return m.ServerLogsCookie
	}
	return nil
}

func (m *BrowseTab) GetListUrl() string {
	if m != nil && m.ListUrl != nil {
		return *m.ListUrl
	}
	return ""
}

func (m *BrowseTab) GetCategory() []*BrowseLink {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *BrowseTab) GetQuickLink() []*QuickLink {
	if m != nil {
		return m.QuickLink
	}
	return nil
}

func (m *BrowseTab) GetQuickLinkTitle() string {
	if m != nil && m.QuickLinkTitle != nil {
		return *m.QuickLinkTitle
	}
	return ""
}

func (m *BrowseTab) GetCategoriesTitle() string {
	if m != nil && m.CategoriesTitle != nil {
		return *m.CategoriesTitle
	}
	return ""
}

func (m *BrowseTab) GetBackendId() int32 {
	if m != nil && m.BackendId != nil {
		return *m.BackendId
	}
	return 0
}

func (m *BrowseTab) GetHighlightsBannerUrl() string {
	if m != nil && m.HighlightsBannerUrl != nil {
		return *m.HighlightsBannerUrl
	}
	return ""
}

func (m *BrowseTab) GetEntertainmentTabBubble() *TabBubble {
	if m != nil {
		return m.EntertainmentTabBubble
	}
	return nil
}

type BrowseLink struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DataUrl              *string  `protobuf:"bytes,3,opt,name=dataUrl" json:"dataUrl,omitempty"`
	ServerLogsCookie     []byte   `protobuf:"bytes,4,opt,name=serverLogsCookie" json:"serverLogsCookie,omitempty"`
	Image                *Image   `protobuf:"bytes,5,opt,name=image" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseLink) Reset()         { *m = BrowseLink{} }
func (m *BrowseLink) String() string { return proto.CompactTextString(m) }
func (*BrowseLink) ProtoMessage()    {}
func (*BrowseLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf455f9497dac02, []int{2}
}

func (m *BrowseLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseLink.Unmarshal(m, b)
}
func (m *BrowseLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseLink.Marshal(b, m, deterministic)
}
func (m *BrowseLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseLink.Merge(m, src)
}
func (m *BrowseLink) XXX_Size() int {
	return xxx_messageInfo_BrowseLink.Size(m)
}
func (m *BrowseLink) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseLink.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseLink proto.InternalMessageInfo

func (m *BrowseLink) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BrowseLink) GetDataUrl() string {
	if m != nil && m.DataUrl != nil {
		return *m.DataUrl
	}
	return ""
}

func (m *BrowseLink) GetServerLogsCookie() []byte {
	if m != nil {
		return m.ServerLogsCookie
	}
	return nil
}

func (m *BrowseLink) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type QuickLink struct {
	Name                 *string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image                *Image        `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Link                 *ResolvedLink `protobuf:"bytes,3,opt,name=link" json:"link,omitempty"`
	DisplayRequired      *bool         `protobuf:"varint,4,opt,name=displayRequired" json:"displayRequired,omitempty"`
	ServerLogsCookie     []byte        `protobuf:"bytes,5,opt,name=serverLogsCookie" json:"serverLogsCookie,omitempty"`
	BackendId            *int32        `protobuf:"varint,6,opt,name=backendId" json:"backendId,omitempty"`
	PrismStyle           *bool         `protobuf:"varint,7,opt,name=prismStyle" json:"prismStyle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QuickLink) Reset()         { *m = QuickLink{} }
func (m *QuickLink) String() string { return proto.CompactTextString(m) }
func (*QuickLink) ProtoMessage()    {}
func (*QuickLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf455f9497dac02, []int{3}
}

func (m *QuickLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuickLink.Unmarshal(m, b)
}
func (m *QuickLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuickLink.Marshal(b, m, deterministic)
}
func (m *QuickLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuickLink.Merge(m, src)
}
func (m *QuickLink) XXX_Size() int {
	return xxx_messageInfo_QuickLink.Size(m)
}
func (m *QuickLink) XXX_DiscardUnknown() {
	xxx_messageInfo_QuickLink.DiscardUnknown(m)
}

var xxx_messageInfo_QuickLink proto.InternalMessageInfo

func (m *QuickLink) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *QuickLink) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *QuickLink) GetLink() *ResolvedLink {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *QuickLink) GetDisplayRequired() bool {
	if m != nil && m.DisplayRequired != nil {
		return *m.DisplayRequired
	}
	return false
}

func (m *QuickLink) GetServerLogsCookie() []byte {
	if m != nil {
		return m.ServerLogsCookie
	}
	return nil
}

func (m *QuickLink) GetBackendId() int32 {
	if m != nil && m.BackendId != nil {
		return *m.BackendId
	}
	return 0
}

func (m *QuickLink) GetPrismStyle() bool {
	if m != nil && m.PrismStyle != nil {
		return *m.PrismStyle
	}
	return false
}

type TabBubble struct {
	Text                 *string  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TabBubble) Reset()         { *m = TabBubble{} }
func (m *TabBubble) String() string { return proto.CompactTextString(m) }
func (*TabBubble) ProtoMessage()    {}
func (*TabBubble) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf455f9497dac02, []int{4}
}

func (m *TabBubble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TabBubble.Unmarshal(m, b)
}
func (m *TabBubble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TabBubble.Marshal(b, m, deterministic)
}
func (m *TabBubble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TabBubble.Merge(m, src)
}
func (m *TabBubble) XXX_Size() int {
	return xxx_messageInfo_TabBubble.Size(m)
}
func (m *TabBubble) XXX_DiscardUnknown() {
	xxx_messageInfo_TabBubble.DiscardUnknown(m)
}

var xxx_messageInfo_TabBubble proto.InternalMessageInfo

func (m *TabBubble) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*BrowseResponse)(nil), "playapi.proto.finsky.browse.BrowseResponse")
	proto.RegisterType((*BrowseTab)(nil), "playapi.proto.finsky.browse.BrowseTab")
	proto.RegisterType((*BrowseLink)(nil), "playapi.proto.finsky.browse.BrowseLink")
	proto.RegisterType((*QuickLink)(nil), "playapi.proto.finsky.browse.QuickLink")
	proto.RegisterType((*TabBubble)(nil), "playapi.proto.finsky.browse.TabBubble")
}

func init() { proto.RegisterFile("play_browse.proto", fileDescriptor_ccf455f9497dac02) }

var fileDescriptor_ccf455f9497dac02 = []byte{
	// 658 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x4f, 0x13, 0x41,
	0x14, 0x4f, 0xff, 0x2c, 0x74, 0x1f, 0x04, 0x64, 0x34, 0x66, 0x05, 0x23, 0xb5, 0x07, 0x6c, 0x8c,
	0x29, 0xea, 0x55, 0x4f, 0x85, 0x60, 0x30, 0x5c, 0x1c, 0xea, 0xc5, 0x83, 0x66, 0x76, 0xf7, 0xb1,
	0x9d, 0x74, 0x76, 0xa6, 0xcc, 0x4c, 0x91, 0x7e, 0x14, 0x2f, 0x5e, 0xfc, 0x8a, 0x7e, 0x00, 0x33,
	0xb3, 0x74, 0x5b, 0x4a, 0x0b, 0x68, 0xbc, 0xed, 0xfb, 0xbd, 0xdf, 0xfb, 0xff, 0xdb, 0x81, 0xad,
	0xa1, 0x60, 0xe3, 0x6f, 0xb1, 0x56, 0xdf, 0x0d, 0x76, 0x86, 0x5a, 0x59, 0x45, 0x76, 0x1c, 0xc4,
	0x86, 0xbc, 0x30, 0x3b, 0x67, 0x5c, 0x9a, 0xc1, 0xb8, 0x53, 0x50, 0xb6, 0x0b, 0x7e, 0xa2, 0xf2,
	0x5c, 0xc9, 0x82, 0xb0, 0xbd, 0xe9, 0x21, 0xc1, 0xe5, 0xa0, 0x00, 0x5a, 0x3f, 0x03, 0xd8, 0xe8,
	0x7a, 0x3a, 0x45, 0x33, 0x54, 0xd2, 0x20, 0x69, 0xc2, 0x5a, 0xa2, 0xa4, 0x45, 0x69, 0xcd, 0x67,
	0x2d, 0xa2, 0x4a, 0xb3, 0xd2, 0x0e, 0xe9, 0x2c, 0x44, 0xb6, 0xa1, 0x31, 0xd4, 0x2a, 0x57, 0xce,
	0x5d, 0xf5, 0xee, 0xd2, 0x26, 0x07, 0xd0, 0x48, 0x98, 0xc5, 0x4c, 0xe9, 0x71, 0x54, 0x6b, 0xd6,
	0xda, 0x6b, 0x6f, 0x5f, 0x74, 0x6e, 0x69, 0xb2, 0x53, 0x14, 0x3f, 0xe1, 0x72, 0x40, 0xcb, 0x40,
	0xf2, 0x01, 0x20, 0xd6, 0xc8, 0xd2, 0x44, 0x8f, 0xf2, 0x38, 0xaa, 0xff, 0x5d, 0x9a, 0x99, 0x50,
	0x72, 0x08, 0xe1, 0xf9, 0x88, 0x27, 0x03, 0xe7, 0x88, 0x02, 0x9f, 0x67, 0xef, 0xd6, 0x3c, 0x9f,
	0x26, 0x6c, 0x3a, 0x0d, 0x24, 0x2f, 0xe1, 0x81, 0x41, 0x7d, 0x81, 0xfa, 0x44, 0x65, 0xe6, 0x40,
	0xa9, 0x01, 0xc7, 0x68, 0xa5, 0x59, 0x69, 0xaf, 0xd3, 0x1b, 0x38, 0x79, 0x04, 0x81, 0xe5, 0x56,
	0x60, 0xb4, 0xea, 0x17, 0x53, 0x18, 0xe4, 0x29, 0x84, 0x31, 0x4b, 0x06, 0x28, 0xd3, 0xe3, 0x34,
	0x6a, 0x34, 0x2b, 0xed, 0x80, 0x4e, 0x01, 0xd7, 0x65, 0x51, 0xbe, 0xc7, 0xe2, 0x28, 0xbc, 0x47,
	0x97, 0xdd, 0x09, 0x9b, 0x4e, 0x03, 0x49, 0x1b, 0x36, 0x05, 0x93, 0x29, 0x97, 0x59, 0x8f, 0xc5,
	0xc7, 0x32, 0xc5, 0xcb, 0x08, 0x7c, 0xa5, 0x79, 0x98, 0xbc, 0x82, 0xad, 0x72, 0xb8, 0x92, 0xbb,
	0xe6, 0xb9, 0x37, 0x1d, 0xe4, 0x3d, 0x3c, 0x29, 0xc1, 0x23, 0x26, 0x84, 0xeb, 0xbb, 0x8c, 0x5a,
	0xf7, 0x51, 0xcb, 0x09, 0xa4, 0x05, 0xeb, 0xdc, 0x1c, 0xb1, 0x9c, 0x8b, 0xf1, 0x29, 0x3b, 0xc3,
	0x68, 0xa3, 0x59, 0x69, 0x37, 0xe8, 0x35, 0xcc, 0xe9, 0xc9, 0xb2, 0xf8, 0xd4, 0x8e, 0x05, 0x46,
	0x9b, 0x3e, 0x61, 0x69, 0xb7, 0x7e, 0xd7, 0x20, 0x2c, 0xc7, 0x9d, 0x6e, 0xb7, 0x32, 0xbb, 0xdd,
	0x45, 0xf7, 0xa9, 0x2e, 0xb9, 0x4f, 0x04, 0xab, 0x82, 0x1b, 0xeb, 0xa4, 0x5b, 0xf3, 0x39, 0x26,
	0xe6, 0x35, 0xe5, 0xd6, 0xff, 0x55, 0xb9, 0xff, 0x47, 0x70, 0x7b, 0xb0, 0x31, 0xbd, 0x83, 0x9f,
	0x77, 0xc5, 0xf7, 0x3a, 0x87, 0xba, 0x93, 0x5f, 0x55, 0xe6, 0x68, 0x7a, 0x33, 0xb2, 0x9b, 0x87,
	0xef, 0x10, 0xe0, 0x6b, 0x78, 0xd8, 0xe7, 0x59, 0x5f, 0xf0, 0xac, 0x6f, 0x4d, 0x97, 0x49, 0x89,
	0xda, 0x2d, 0x28, 0xf4, 0xb9, 0x16, 0xb9, 0xc8, 0x57, 0x78, 0x8c, 0xd2, 0xa2, 0xb6, 0x8c, 0xcb,
	0x1c, 0xa5, 0xed, 0xb1, 0xb8, 0x3b, 0x8a, 0x63, 0x81, 0x5e, 0x73, 0x77, 0x0d, 0x5d, 0xb2, 0xe9,
	0x92, 0x2c, 0xad, 0x1f, 0x15, 0x80, 0xe9, 0x82, 0x09, 0x81, 0xba, 0x64, 0xf9, 0xe4, 0xec, 0xfe,
	0xdb, 0x5d, 0x32, 0x65, 0x96, 0xcd, 0x5c, 0xf2, 0xca, 0x5c, 0xa8, 0x87, 0xfa, 0x12, 0x3d, 0xbc,
	0x81, 0x80, 0xe7, 0x2c, 0xc3, 0x28, 0xf0, 0x7d, 0xef, 0x2c, 0xee, 0xfb, 0xd8, 0x51, 0x68, 0xc1,
	0x6c, 0xfd, 0xaa, 0x42, 0x58, 0x9e, 0x6d, 0x61, 0x6b, 0x65, 0xd2, 0xea, 0x7d, 0x93, 0x92, 0x77,
	0x50, 0x77, 0xcf, 0xb2, 0x1f, 0x65, 0xa9, 0xf2, 0xfc, 0xc3, 0x4d, 0xd1, 0x28, 0x71, 0x81, 0xa9,
	0x17, 0x8d, 0x0f, 0x72, 0x3a, 0x48, 0xb9, 0x71, 0x21, 0x14, 0xcf, 0x47, 0x5c, 0x63, 0xea, 0xe7,
	0x6d, 0xd0, 0x79, 0x78, 0xe1, 0x6a, 0x82, 0x25, 0xab, 0xb9, 0xa6, 0x99, 0x95, 0x79, 0xcd, 0x3c,
	0x03, 0x18, 0x6a, 0x6e, 0xf2, 0xe2, 0xb7, 0x5d, 0xf5, 0xe5, 0x66, 0x90, 0xd6, 0x2e, 0x84, 0xe5,
	0x39, 0xdd, 0x92, 0x2c, 0x5e, 0xda, 0xc9, 0x92, 0xdc, 0x77, 0xf7, 0xf9, 0x97, 0xdd, 0x8c, 0xdb,
	0xfe, 0x28, 0xee, 0x24, 0x2a, 0xdf, 0xff, 0xa8, 0x4c, 0x7f, 0xc4, 0x0e, 0x15, 0x9a, 0x7d, 0xc1,
	0x63, 0x8d, 0xae, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0x7a, 0x51, 0xd6, 0xf2, 0x06,
	0x00, 0x00,
}
