// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gsf.proto

// generated with https://github.com/egirault/googleplay-api/blob/master/androguard/androproto.py
// then modified a bit by hand to add the new fields that were added after the move to gms from gsf
// also look at https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/protos-repo/checkin.proto

package libplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AndroidCheckinRequest struct {
	Imei                  *string                   `protobuf:"bytes,1,opt,name=imei" json:"imei,omitempty"`
	Id                    *int64                    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Digest                *string                   `protobuf:"bytes,3,opt,name=digest" json:"digest,omitempty"`
	Checkin               *AndroidCheckinProto      `protobuf:"bytes,4,opt,name=checkin" json:"checkin,omitempty"`
	DesiredBuild          *string                   `protobuf:"bytes,5,opt,name=desiredBuild" json:"desiredBuild,omitempty"`
	Locale                *string                   `protobuf:"bytes,6,opt,name=locale" json:"locale,omitempty"`
	LoggingId             *int64                    `protobuf:"varint,7,opt,name=loggingId" json:"loggingId,omitempty"`
	MarketCheckin         *string                   `protobuf:"bytes,8,opt,name=marketCheckin" json:"marketCheckin,omitempty"`
	MacAddr               []string                  `protobuf:"bytes,9,rep,name=macAddr" json:"macAddr,omitempty"`
	Meid                  *string                   `protobuf:"bytes,10,opt,name=meid" json:"meid,omitempty"`
	AccountCookie         []string                  `protobuf:"bytes,11,rep,name=accountCookie" json:"accountCookie,omitempty"`
	TimeZone              *string                   `protobuf:"bytes,12,opt,name=timeZone" json:"timeZone,omitempty"`
	SecurityToken         *uint64                   `protobuf:"fixed64,13,opt,name=securityToken" json:"securityToken,omitempty"`
	Version               *int32                    `protobuf:"varint,14,opt,name=version" json:"version,omitempty"`
	OtaCert               []string                  `protobuf:"bytes,15,rep,name=otaCert" json:"otaCert,omitempty"`
	SerialNumber          *string                   `protobuf:"bytes,16,opt,name=serialNumber" json:"serialNumber,omitempty"`
	Esn                   *string                   `protobuf:"bytes,17,opt,name=esn" json:"esn,omitempty"`
	DeviceConfiguration   *DeviceConfigurationProto `protobuf:"bytes,18,opt,name=deviceConfiguration" json:"deviceConfiguration,omitempty"`
	MacAddrType           []string                  `protobuf:"bytes,19,rep,name=macAddrType" json:"macAddrType,omitempty"`
	Fragment              *int32                    `protobuf:"varint,20,opt,name=fragment" json:"fragment,omitempty"`
	UserName              *string                   `protobuf:"bytes,21,opt,name=userName" json:"userName,omitempty"`
	UserSerialNumber      *int32                    `protobuf:"varint,22,opt,name=userSerialNumber" json:"userSerialNumber,omitempty"`
	DroidguardResult      *string                   `protobuf:"bytes,24,opt,name=droidguardResult" json:"droidguardResult,omitempty"`
	DeviceDataVersionInfo *string                   `protobuf:"bytes,25,opt,name=deviceDataVersionInfo" json:"deviceDataVersionInfo,omitempty"`
	FetchSystemUpdates    *bool                     `protobuf:"varint,29,opt,name=fetchSystemUpdates" json:"fetchSystemUpdates,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *AndroidCheckinRequest) Reset()         { *m = AndroidCheckinRequest{} }
func (m *AndroidCheckinRequest) String() string { return proto.CompactTextString(m) }
func (*AndroidCheckinRequest) ProtoMessage()    {}
func (*AndroidCheckinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{0}
}

func (m *AndroidCheckinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidCheckinRequest.Unmarshal(m, b)
}
func (m *AndroidCheckinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidCheckinRequest.Marshal(b, m, deterministic)
}
func (m *AndroidCheckinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidCheckinRequest.Merge(m, src)
}
func (m *AndroidCheckinRequest) XXX_Size() int {
	return xxx_messageInfo_AndroidCheckinRequest.Size(m)
}
func (m *AndroidCheckinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidCheckinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidCheckinRequest proto.InternalMessageInfo

func (m *AndroidCheckinRequest) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *AndroidCheckinRequest) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AndroidCheckinRequest) GetDigest() string {
	if m != nil && m.Digest != nil {
		return *m.Digest
	}
	return ""
}

func (m *AndroidCheckinRequest) GetCheckin() *AndroidCheckinProto {
	if m != nil {
		return m.Checkin
	}
	return nil
}

func (m *AndroidCheckinRequest) GetDesiredBuild() string {
	if m != nil && m.DesiredBuild != nil {
		return *m.DesiredBuild
	}
	return ""
}

func (m *AndroidCheckinRequest) GetLocale() string {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return ""
}

func (m *AndroidCheckinRequest) GetLoggingId() int64 {
	if m != nil && m.LoggingId != nil {
		return *m.LoggingId
	}
	return 0
}

func (m *AndroidCheckinRequest) GetMarketCheckin() string {
	if m != nil && m.MarketCheckin != nil {
		return *m.MarketCheckin
	}
	return ""
}

func (m *AndroidCheckinRequest) GetMacAddr() []string {
	if m != nil {
		return m.MacAddr
	}
	return nil
}

func (m *AndroidCheckinRequest) GetMeid() string {
	if m != nil && m.Meid != nil {
		return *m.Meid
	}
	return ""
}

func (m *AndroidCheckinRequest) GetAccountCookie() []string {
	if m != nil {
		return m.AccountCookie
	}
	return nil
}

func (m *AndroidCheckinRequest) GetTimeZone() string {
	if m != nil && m.TimeZone != nil {
		return *m.TimeZone
	}
	return ""
}

func (m *AndroidCheckinRequest) GetSecurityToken() uint64 {
	if m != nil && m.SecurityToken != nil {
		return *m.SecurityToken
	}
	return 0
}

func (m *AndroidCheckinRequest) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AndroidCheckinRequest) GetOtaCert() []string {
	if m != nil {
		return m.OtaCert
	}
	return nil
}

func (m *AndroidCheckinRequest) GetSerialNumber() string {
	if m != nil && m.SerialNumber != nil {
		return *m.SerialNumber
	}
	return ""
}

func (m *AndroidCheckinRequest) GetEsn() string {
	if m != nil && m.Esn != nil {
		return *m.Esn
	}
	return ""
}

func (m *AndroidCheckinRequest) GetDeviceConfiguration() *DeviceConfigurationProto {
	if m != nil {
		return m.DeviceConfiguration
	}
	return nil
}

func (m *AndroidCheckinRequest) GetMacAddrType() []string {
	if m != nil {
		return m.MacAddrType
	}
	return nil
}

func (m *AndroidCheckinRequest) GetFragment() int32 {
	if m != nil && m.Fragment != nil {
		return *m.Fragment
	}
	return 0
}

func (m *AndroidCheckinRequest) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *AndroidCheckinRequest) GetUserSerialNumber() int32 {
	if m != nil && m.UserSerialNumber != nil {
		return *m.UserSerialNumber
	}
	return 0
}

func (m *AndroidCheckinRequest) GetDroidguardResult() string {
	if m != nil && m.DroidguardResult != nil {
		return *m.DroidguardResult
	}
	return ""
}

func (m *AndroidCheckinRequest) GetDeviceDataVersionInfo() string {
	if m != nil && m.DeviceDataVersionInfo != nil {
		return *m.DeviceDataVersionInfo
	}
	return ""
}

func (m *AndroidCheckinRequest) GetFetchSystemUpdates() bool {
	if m != nil && m.FetchSystemUpdates != nil {
		return *m.FetchSystemUpdates
	}
	return false
}

type AndroidCheckinResponse struct {
	StatsOk               *bool                 `protobuf:"varint,1,opt,name=statsOk" json:"statsOk,omitempty"`
	Intent                []*AndroidIntentProto `protobuf:"bytes,2,rep,name=intent" json:"intent,omitempty"`
	TimeMsec              *int64                `protobuf:"varint,3,opt,name=timeMsec" json:"timeMsec,omitempty"`
	Digest                *string               `protobuf:"bytes,4,opt,name=digest" json:"digest,omitempty"`
	Setting               []*GservicesSetting   `protobuf:"bytes,5,rep,name=setting" json:"setting,omitempty"`
	MarketOk              *bool                 `protobuf:"varint,6,opt,name=marketOk" json:"marketOk,omitempty"`
	AndroidId             *uint64               `protobuf:"fixed64,7,opt,name=androidId" json:"androidId,omitempty"`
	SecurityToken         *uint64               `protobuf:"fixed64,8,opt,name=securityToken" json:"securityToken,omitempty"`
	SettingsDiff          *bool                 `protobuf:"varint,9,opt,name=settingsDiff" json:"settingsDiff,omitempty"`
	DeleteSetting         []string              `protobuf:"bytes,10,rep,name=deleteSetting" json:"deleteSetting,omitempty"`
	DeviceDataVersionInfo *string               `protobuf:"bytes,12,opt,name=deviceDataVersionInfo" json:"deviceDataVersionInfo,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *AndroidCheckinResponse) Reset()         { *m = AndroidCheckinResponse{} }
func (m *AndroidCheckinResponse) String() string { return proto.CompactTextString(m) }
func (*AndroidCheckinResponse) ProtoMessage()    {}
func (*AndroidCheckinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{1}
}

func (m *AndroidCheckinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidCheckinResponse.Unmarshal(m, b)
}
func (m *AndroidCheckinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidCheckinResponse.Marshal(b, m, deterministic)
}
func (m *AndroidCheckinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidCheckinResponse.Merge(m, src)
}
func (m *AndroidCheckinResponse) XXX_Size() int {
	return xxx_messageInfo_AndroidCheckinResponse.Size(m)
}
func (m *AndroidCheckinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidCheckinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidCheckinResponse proto.InternalMessageInfo

func (m *AndroidCheckinResponse) GetStatsOk() bool {
	if m != nil && m.StatsOk != nil {
		return *m.StatsOk
	}
	return false
}

func (m *AndroidCheckinResponse) GetIntent() []*AndroidIntentProto {
	if m != nil {
		return m.Intent
	}
	return nil
}

func (m *AndroidCheckinResponse) GetTimeMsec() int64 {
	if m != nil && m.TimeMsec != nil {
		return *m.TimeMsec
	}
	return 0
}

func (m *AndroidCheckinResponse) GetDigest() string {
	if m != nil && m.Digest != nil {
		return *m.Digest
	}
	return ""
}

func (m *AndroidCheckinResponse) GetSetting() []*GservicesSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

func (m *AndroidCheckinResponse) GetMarketOk() bool {
	if m != nil && m.MarketOk != nil {
		return *m.MarketOk
	}
	return false
}

func (m *AndroidCheckinResponse) GetAndroidId() uint64 {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return 0
}

func (m *AndroidCheckinResponse) GetSecurityToken() uint64 {
	if m != nil && m.SecurityToken != nil {
		return *m.SecurityToken
	}
	return 0
}

func (m *AndroidCheckinResponse) GetSettingsDiff() bool {
	if m != nil && m.SettingsDiff != nil {
		return *m.SettingsDiff
	}
	return false
}

func (m *AndroidCheckinResponse) GetDeleteSetting() []string {
	if m != nil {
		return m.DeleteSetting
	}
	return nil
}

func (m *AndroidCheckinResponse) GetDeviceDataVersionInfo() string {
	if m != nil && m.DeviceDataVersionInfo != nil {
		return *m.DeviceDataVersionInfo
	}
	return ""
}

type GservicesSetting struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GservicesSetting) Reset()         { *m = GservicesSetting{} }
func (m *GservicesSetting) String() string { return proto.CompactTextString(m) }
func (*GservicesSetting) ProtoMessage()    {}
func (*GservicesSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{2}
}

func (m *GservicesSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GservicesSetting.Unmarshal(m, b)
}
func (m *GservicesSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GservicesSetting.Marshal(b, m, deterministic)
}
func (m *GservicesSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GservicesSetting.Merge(m, src)
}
func (m *GservicesSetting) XXX_Size() int {
	return xxx_messageInfo_GservicesSetting.Size(m)
}
func (m *GservicesSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GservicesSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GservicesSetting proto.InternalMessageInfo

func (m *GservicesSetting) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GservicesSetting) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeviceConfigurationProto struct {
	TouchScreen               *int32                                           `protobuf:"varint,1,opt,name=touchScreen" json:"touchScreen,omitempty"`
	Keyboard                  *int32                                           `protobuf:"varint,2,opt,name=keyboard" json:"keyboard,omitempty"`
	Navigation                *int32                                           `protobuf:"varint,3,opt,name=navigation" json:"navigation,omitempty"`
	ScreenLayout              *int32                                           `protobuf:"varint,4,opt,name=screenLayout" json:"screenLayout,omitempty"`
	HasHardKeyboard           *bool                                            `protobuf:"varint,5,opt,name=hasHardKeyboard" json:"hasHardKeyboard,omitempty"`
	HasFiveWayNavigation      *bool                                            `protobuf:"varint,6,opt,name=hasFiveWayNavigation" json:"hasFiveWayNavigation,omitempty"`
	ScreenDensity             *int32                                           `protobuf:"varint,7,opt,name=screenDensity" json:"screenDensity,omitempty"`
	GlEsVersion               *int32                                           `protobuf:"varint,8,opt,name=glEsVersion" json:"glEsVersion,omitempty"`
	SystemSharedLibrary       []string                                         `protobuf:"bytes,9,rep,name=systemSharedLibrary" json:"systemSharedLibrary,omitempty"`
	SystemAvailableFeature    []string                                         `protobuf:"bytes,10,rep,name=systemAvailableFeature" json:"systemAvailableFeature,omitempty"`
	NativePlatform            []string                                         `protobuf:"bytes,11,rep,name=nativePlatform" json:"nativePlatform,omitempty"`
	ScreenWidth               *int32                                           `protobuf:"varint,12,opt,name=screenWidth" json:"screenWidth,omitempty"`
	ScreenHeight              *int32                                           `protobuf:"varint,13,opt,name=screenHeight" json:"screenHeight,omitempty"`
	SystemSupportedLocale     []string                                         `protobuf:"bytes,14,rep,name=systemSupportedLocale" json:"systemSupportedLocale,omitempty"`
	GlExtension               []string                                         `protobuf:"bytes,15,rep,name=glExtension" json:"glExtension,omitempty"`
	MaxApkDownloadSizeMb      *int32                                           `protobuf:"varint,17,opt,name=maxApkDownloadSizeMb" json:"maxApkDownloadSizeMb,omitempty"`
	SmallestScreenWidthDp     *int32                                           `protobuf:"varint,18,opt,name=smallestScreenWidthDp" json:"smallestScreenWidthDp,omitempty"`
	LowRamDevice              *bool                                            `protobuf:"varint,19,opt,name=lowRamDevice" json:"lowRamDevice,omitempty"`
	TotalMemoryBytes          *int64                                           `protobuf:"varint,20,opt,name=totalMemoryBytes" json:"totalMemoryBytes,omitempty"`
	MaxNumOfCpuCores          *int32                                           `protobuf:"varint,21,opt,name=maxNumOfCpuCores" json:"maxNumOfCpuCores,omitempty"`
	NewSystemAvailableFeature []*DeviceConfigurationProto_FeatureWithGLVersion `protobuf:"bytes,26,rep,name=newSystemAvailableFeature" json:"newSystemAvailableFeature,omitempty"`
	KeyguardDeviceSecure      *bool                                            `protobuf:"varint,28,opt,name=keyguardDeviceSecure" json:"keyguardDeviceSecure,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                         `json:"-"`
	XXX_unrecognized          []byte                                           `json:"-"`
	XXX_sizecache             int32                                            `json:"-"`
}

func (m *DeviceConfigurationProto) Reset()         { *m = DeviceConfigurationProto{} }
func (m *DeviceConfigurationProto) String() string { return proto.CompactTextString(m) }
func (*DeviceConfigurationProto) ProtoMessage()    {}
func (*DeviceConfigurationProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{3}
}

func (m *DeviceConfigurationProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceConfigurationProto.Unmarshal(m, b)
}
func (m *DeviceConfigurationProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceConfigurationProto.Marshal(b, m, deterministic)
}
func (m *DeviceConfigurationProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConfigurationProto.Merge(m, src)
}
func (m *DeviceConfigurationProto) XXX_Size() int {
	return xxx_messageInfo_DeviceConfigurationProto.Size(m)
}
func (m *DeviceConfigurationProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConfigurationProto.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConfigurationProto proto.InternalMessageInfo

func (m *DeviceConfigurationProto) GetTouchScreen() int32 {
	if m != nil && m.TouchScreen != nil {
		return *m.TouchScreen
	}
	return 0
}

func (m *DeviceConfigurationProto) GetKeyboard() int32 {
	if m != nil && m.Keyboard != nil {
		return *m.Keyboard
	}
	return 0
}

func (m *DeviceConfigurationProto) GetNavigation() int32 {
	if m != nil && m.Navigation != nil {
		return *m.Navigation
	}
	return 0
}

func (m *DeviceConfigurationProto) GetScreenLayout() int32 {
	if m != nil && m.ScreenLayout != nil {
		return *m.ScreenLayout
	}
	return 0
}

func (m *DeviceConfigurationProto) GetHasHardKeyboard() bool {
	if m != nil && m.HasHardKeyboard != nil {
		return *m.HasHardKeyboard
	}
	return false
}

func (m *DeviceConfigurationProto) GetHasFiveWayNavigation() bool {
	if m != nil && m.HasFiveWayNavigation != nil {
		return *m.HasFiveWayNavigation
	}
	return false
}

func (m *DeviceConfigurationProto) GetScreenDensity() int32 {
	if m != nil && m.ScreenDensity != nil {
		return *m.ScreenDensity
	}
	return 0
}

func (m *DeviceConfigurationProto) GetGlEsVersion() int32 {
	if m != nil && m.GlEsVersion != nil {
		return *m.GlEsVersion
	}
	return 0
}

func (m *DeviceConfigurationProto) GetSystemSharedLibrary() []string {
	if m != nil {
		return m.SystemSharedLibrary
	}
	return nil
}

func (m *DeviceConfigurationProto) GetSystemAvailableFeature() []string {
	if m != nil {
		return m.SystemAvailableFeature
	}
	return nil
}

func (m *DeviceConfigurationProto) GetNativePlatform() []string {
	if m != nil {
		return m.NativePlatform
	}
	return nil
}

func (m *DeviceConfigurationProto) GetScreenWidth() int32 {
	if m != nil && m.ScreenWidth != nil {
		return *m.ScreenWidth
	}
	return 0
}

func (m *DeviceConfigurationProto) GetScreenHeight() int32 {
	if m != nil && m.ScreenHeight != nil {
		return *m.ScreenHeight
	}
	return 0
}

func (m *DeviceConfigurationProto) GetSystemSupportedLocale() []string {
	if m != nil {
		return m.SystemSupportedLocale
	}
	return nil
}

func (m *DeviceConfigurationProto) GetGlExtension() []string {
	if m != nil {
		return m.GlExtension
	}
	return nil
}

func (m *DeviceConfigurationProto) GetMaxApkDownloadSizeMb() int32 {
	if m != nil && m.MaxApkDownloadSizeMb != nil {
		return *m.MaxApkDownloadSizeMb
	}
	return 0
}

func (m *DeviceConfigurationProto) GetSmallestScreenWidthDp() int32 {
	if m != nil && m.SmallestScreenWidthDp != nil {
		return *m.SmallestScreenWidthDp
	}
	return 0
}

func (m *DeviceConfigurationProto) GetLowRamDevice() bool {
	if m != nil && m.LowRamDevice != nil {
		return *m.LowRamDevice
	}
	return false
}

func (m *DeviceConfigurationProto) GetTotalMemoryBytes() int64 {
	if m != nil && m.TotalMemoryBytes != nil {
		return *m.TotalMemoryBytes
	}
	return 0
}

func (m *DeviceConfigurationProto) GetMaxNumOfCpuCores() int32 {
	if m != nil && m.MaxNumOfCpuCores != nil {
		return *m.MaxNumOfCpuCores
	}
	return 0
}

func (m *DeviceConfigurationProto) GetNewSystemAvailableFeature() []*DeviceConfigurationProto_FeatureWithGLVersion {
	if m != nil {
		return m.NewSystemAvailableFeature
	}
	return nil
}

func (m *DeviceConfigurationProto) GetKeyguardDeviceSecure() bool {
	if m != nil && m.KeyguardDeviceSecure != nil {
		return *m.KeyguardDeviceSecure
	}
	return false
}

type DeviceConfigurationProto_FeatureWithGLVersion struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	GlEsVersion          *int32   `protobuf:"varint,2,opt,name=glEsVersion" json:"glEsVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceConfigurationProto_FeatureWithGLVersion) Reset() {
	*m = DeviceConfigurationProto_FeatureWithGLVersion{}
}
func (m *DeviceConfigurationProto_FeatureWithGLVersion) String() string {
	return proto.CompactTextString(m)
}
func (*DeviceConfigurationProto_FeatureWithGLVersion) ProtoMessage() {}
func (*DeviceConfigurationProto_FeatureWithGLVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{3, 0}
}

func (m *DeviceConfigurationProto_FeatureWithGLVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceConfigurationProto_FeatureWithGLVersion.Unmarshal(m, b)
}
func (m *DeviceConfigurationProto_FeatureWithGLVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceConfigurationProto_FeatureWithGLVersion.Marshal(b, m, deterministic)
}
func (m *DeviceConfigurationProto_FeatureWithGLVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConfigurationProto_FeatureWithGLVersion.Merge(m, src)
}
func (m *DeviceConfigurationProto_FeatureWithGLVersion) XXX_Size() int {
	return xxx_messageInfo_DeviceConfigurationProto_FeatureWithGLVersion.Size(m)
}
func (m *DeviceConfigurationProto_FeatureWithGLVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConfigurationProto_FeatureWithGLVersion.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConfigurationProto_FeatureWithGLVersion proto.InternalMessageInfo

func (m *DeviceConfigurationProto_FeatureWithGLVersion) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DeviceConfigurationProto_FeatureWithGLVersion) GetGlEsVersion() int32 {
	if m != nil && m.GlEsVersion != nil {
		return *m.GlEsVersion
	}
	return 0
}

type AndroidBuildProto struct {
	Id                   *string                             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Product              *string                             `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Carrier              *string                             `protobuf:"bytes,3,opt,name=carrier" json:"carrier,omitempty"`
	Radio                *string                             `protobuf:"bytes,4,opt,name=radio" json:"radio,omitempty"`
	Bootloader           *string                             `protobuf:"bytes,5,opt,name=bootloader" json:"bootloader,omitempty"`
	Client               *string                             `protobuf:"bytes,6,opt,name=client" json:"client,omitempty"`
	Timestamp            *int64                              `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
	GoogleServices       *int32                              `protobuf:"varint,8,opt,name=googleServices" json:"googleServices,omitempty"`
	Device               *string                             `protobuf:"bytes,9,opt,name=device" json:"device,omitempty"`
	SdkVersion           *int32                              `protobuf:"varint,10,opt,name=sdkVersion" json:"sdkVersion,omitempty"`
	Model                *string                             `protobuf:"bytes,11,opt,name=model" json:"model,omitempty"`
	Manufacturer         *string                             `protobuf:"bytes,12,opt,name=manufacturer" json:"manufacturer,omitempty"`
	BuildProduct         *string                             `protobuf:"bytes,13,opt,name=buildProduct" json:"buildProduct,omitempty"`
	OtaInstalled         *bool                               `protobuf:"varint,14,opt,name=otaInstalled" json:"otaInstalled,omitempty"`
	GooglePackage        []*AndroidBuildProto_PackageVersion `protobuf:"bytes,15,rep,name=googlePackage" json:"googlePackage,omitempty"`
	SecurityPatch        *string                             `protobuf:"bytes,19,opt,name=securityPatch" json:"securityPatch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *AndroidBuildProto) Reset()         { *m = AndroidBuildProto{} }
func (m *AndroidBuildProto) String() string { return proto.CompactTextString(m) }
func (*AndroidBuildProto) ProtoMessage()    {}
func (*AndroidBuildProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{4}
}

func (m *AndroidBuildProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidBuildProto.Unmarshal(m, b)
}
func (m *AndroidBuildProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidBuildProto.Marshal(b, m, deterministic)
}
func (m *AndroidBuildProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidBuildProto.Merge(m, src)
}
func (m *AndroidBuildProto) XXX_Size() int {
	return xxx_messageInfo_AndroidBuildProto.Size(m)
}
func (m *AndroidBuildProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidBuildProto.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidBuildProto proto.InternalMessageInfo

func (m *AndroidBuildProto) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AndroidBuildProto) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *AndroidBuildProto) GetCarrier() string {
	if m != nil && m.Carrier != nil {
		return *m.Carrier
	}
	return ""
}

func (m *AndroidBuildProto) GetRadio() string {
	if m != nil && m.Radio != nil {
		return *m.Radio
	}
	return ""
}

func (m *AndroidBuildProto) GetBootloader() string {
	if m != nil && m.Bootloader != nil {
		return *m.Bootloader
	}
	return ""
}

func (m *AndroidBuildProto) GetClient() string {
	if m != nil && m.Client != nil {
		return *m.Client
	}
	return ""
}

func (m *AndroidBuildProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *AndroidBuildProto) GetGoogleServices() int32 {
	if m != nil && m.GoogleServices != nil {
		return *m.GoogleServices
	}
	return 0
}

func (m *AndroidBuildProto) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *AndroidBuildProto) GetSdkVersion() int32 {
	if m != nil && m.SdkVersion != nil {
		return *m.SdkVersion
	}
	return 0
}

func (m *AndroidBuildProto) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *AndroidBuildProto) GetManufacturer() string {
	if m != nil && m.Manufacturer != nil {
		return *m.Manufacturer
	}
	return ""
}

func (m *AndroidBuildProto) GetBuildProduct() string {
	if m != nil && m.BuildProduct != nil {
		return *m.BuildProduct
	}
	return ""
}

func (m *AndroidBuildProto) GetOtaInstalled() bool {
	if m != nil && m.OtaInstalled != nil {
		return *m.OtaInstalled
	}
	return false
}

func (m *AndroidBuildProto) GetGooglePackage() []*AndroidBuildProto_PackageVersion {
	if m != nil {
		return m.GooglePackage
	}
	return nil
}

func (m *AndroidBuildProto) GetSecurityPatch() string {
	if m != nil && m.SecurityPatch != nil {
		return *m.SecurityPatch
	}
	return ""
}

type AndroidBuildProto_PackageVersion struct {
	Version              *int32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndroidBuildProto_PackageVersion) Reset()         { *m = AndroidBuildProto_PackageVersion{} }
func (m *AndroidBuildProto_PackageVersion) String() string { return proto.CompactTextString(m) }
func (*AndroidBuildProto_PackageVersion) ProtoMessage()    {}
func (*AndroidBuildProto_PackageVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{4, 0}
}

func (m *AndroidBuildProto_PackageVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidBuildProto_PackageVersion.Unmarshal(m, b)
}
func (m *AndroidBuildProto_PackageVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidBuildProto_PackageVersion.Marshal(b, m, deterministic)
}
func (m *AndroidBuildProto_PackageVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidBuildProto_PackageVersion.Merge(m, src)
}
func (m *AndroidBuildProto_PackageVersion) XXX_Size() int {
	return xxx_messageInfo_AndroidBuildProto_PackageVersion.Size(m)
}
func (m *AndroidBuildProto_PackageVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidBuildProto_PackageVersion.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidBuildProto_PackageVersion proto.InternalMessageInfo

func (m *AndroidBuildProto_PackageVersion) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AndroidBuildProto_PackageVersion) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type AndroidCheckinReasonProto struct {
	ReasonType           *int32   `protobuf:"varint,1,opt,name=reasonType" json:"reasonType,omitempty"`
	AttemptCount         *int32   `protobuf:"varint,2,opt,name=attemptCount" json:"attemptCount,omitempty"`
	SourcePackage        *string  `protobuf:"bytes,3,opt,name=sourcePackage" json:"sourcePackage,omitempty"`
	SourceClass          *string  `protobuf:"bytes,4,opt,name=sourceClass" json:"sourceClass,omitempty"`
	SourceForce          *bool    `protobuf:"varint,5,opt,name=sourceForce" json:"sourceForce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndroidCheckinReasonProto) Reset()         { *m = AndroidCheckinReasonProto{} }
func (m *AndroidCheckinReasonProto) String() string { return proto.CompactTextString(m) }
func (*AndroidCheckinReasonProto) ProtoMessage()    {}
func (*AndroidCheckinReasonProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{5}
}

func (m *AndroidCheckinReasonProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidCheckinReasonProto.Unmarshal(m, b)
}
func (m *AndroidCheckinReasonProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidCheckinReasonProto.Marshal(b, m, deterministic)
}
func (m *AndroidCheckinReasonProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidCheckinReasonProto.Merge(m, src)
}
func (m *AndroidCheckinReasonProto) XXX_Size() int {
	return xxx_messageInfo_AndroidCheckinReasonProto.Size(m)
}
func (m *AndroidCheckinReasonProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidCheckinReasonProto.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidCheckinReasonProto proto.InternalMessageInfo

func (m *AndroidCheckinReasonProto) GetReasonType() int32 {
	if m != nil && m.ReasonType != nil {
		return *m.ReasonType
	}
	return 0
}

func (m *AndroidCheckinReasonProto) GetAttemptCount() int32 {
	if m != nil && m.AttemptCount != nil {
		return *m.AttemptCount
	}
	return 0
}

func (m *AndroidCheckinReasonProto) GetSourcePackage() string {
	if m != nil && m.SourcePackage != nil {
		return *m.SourcePackage
	}
	return ""
}

func (m *AndroidCheckinReasonProto) GetSourceClass() string {
	if m != nil && m.SourceClass != nil {
		return *m.SourceClass
	}
	return ""
}

func (m *AndroidCheckinReasonProto) GetSourceForce() bool {
	if m != nil && m.SourceForce != nil {
		return *m.SourceForce
	}
	return false
}

type AndroidCheckinProto struct {
	Build                *AndroidBuildProto         `protobuf:"bytes,1,opt,name=build" json:"build,omitempty"`
	LastCheckinMsec      *int64                     `protobuf:"varint,2,opt,name=lastCheckinMsec" json:"lastCheckinMsec,omitempty"`
	Event                []*AndroidEventProto       `protobuf:"bytes,3,rep,name=event" json:"event,omitempty"`
	Stat                 []*AndroidStatisticProto   `protobuf:"bytes,4,rep,name=stat" json:"stat,omitempty"`
	RequestedGroup       []string                   `protobuf:"bytes,5,rep,name=requestedGroup" json:"requestedGroup,omitempty"`
	CellOperator         *string                    `protobuf:"bytes,6,opt,name=cellOperator" json:"cellOperator,omitempty"`
	SimOperator          *string                    `protobuf:"bytes,7,opt,name=simOperator" json:"simOperator,omitempty"`
	Roaming              *string                    `protobuf:"bytes,8,opt,name=roaming" json:"roaming,omitempty"`
	UserNumber           *int32                     `protobuf:"varint,9,opt,name=userNumber" json:"userNumber,omitempty"`
	DeviceType           *int32                     `protobuf:"varint,14,opt,name=deviceType" json:"deviceType,omitempty"`
	Reason               *AndroidCheckinReasonProto `protobuf:"bytes,15,opt,name=reason" json:"reason,omitempty"`
	VoiceCapable         *bool                      `protobuf:"varint,18,opt,name=voiceCapable" json:"voiceCapable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AndroidCheckinProto) Reset()         { *m = AndroidCheckinProto{} }
func (m *AndroidCheckinProto) String() string { return proto.CompactTextString(m) }
func (*AndroidCheckinProto) ProtoMessage()    {}
func (*AndroidCheckinProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{6}
}

func (m *AndroidCheckinProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidCheckinProto.Unmarshal(m, b)
}
func (m *AndroidCheckinProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidCheckinProto.Marshal(b, m, deterministic)
}
func (m *AndroidCheckinProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidCheckinProto.Merge(m, src)
}
func (m *AndroidCheckinProto) XXX_Size() int {
	return xxx_messageInfo_AndroidCheckinProto.Size(m)
}
func (m *AndroidCheckinProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidCheckinProto.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidCheckinProto proto.InternalMessageInfo

func (m *AndroidCheckinProto) GetBuild() *AndroidBuildProto {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *AndroidCheckinProto) GetLastCheckinMsec() int64 {
	if m != nil && m.LastCheckinMsec != nil {
		return *m.LastCheckinMsec
	}
	return 0
}

func (m *AndroidCheckinProto) GetEvent() []*AndroidEventProto {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *AndroidCheckinProto) GetStat() []*AndroidStatisticProto {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *AndroidCheckinProto) GetRequestedGroup() []string {
	if m != nil {
		return m.RequestedGroup
	}
	return nil
}

func (m *AndroidCheckinProto) GetCellOperator() string {
	if m != nil && m.CellOperator != nil {
		return *m.CellOperator
	}
	return ""
}

func (m *AndroidCheckinProto) GetSimOperator() string {
	if m != nil && m.SimOperator != nil {
		return *m.SimOperator
	}
	return ""
}

func (m *AndroidCheckinProto) GetRoaming() string {
	if m != nil && m.Roaming != nil {
		return *m.Roaming
	}
	return ""
}

func (m *AndroidCheckinProto) GetUserNumber() int32 {
	if m != nil && m.UserNumber != nil {
		return *m.UserNumber
	}
	return 0
}

func (m *AndroidCheckinProto) GetDeviceType() int32 {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

func (m *AndroidCheckinProto) GetReason() *AndroidCheckinReasonProto {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *AndroidCheckinProto) GetVoiceCapable() bool {
	if m != nil && m.VoiceCapable != nil {
		return *m.VoiceCapable
	}
	return false
}

type AndroidEventProto struct {
	Tag                  *string  `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	TimeMsec             *int64   `protobuf:"varint,3,opt,name=timeMsec" json:"timeMsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndroidEventProto) Reset()         { *m = AndroidEventProto{} }
func (m *AndroidEventProto) String() string { return proto.CompactTextString(m) }
func (*AndroidEventProto) ProtoMessage()    {}
func (*AndroidEventProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{7}
}

func (m *AndroidEventProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidEventProto.Unmarshal(m, b)
}
func (m *AndroidEventProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidEventProto.Marshal(b, m, deterministic)
}
func (m *AndroidEventProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidEventProto.Merge(m, src)
}
func (m *AndroidEventProto) XXX_Size() int {
	return xxx_messageInfo_AndroidEventProto.Size(m)
}
func (m *AndroidEventProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidEventProto.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidEventProto proto.InternalMessageInfo

func (m *AndroidEventProto) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *AndroidEventProto) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *AndroidEventProto) GetTimeMsec() int64 {
	if m != nil && m.TimeMsec != nil {
		return *m.TimeMsec
	}
	return 0
}

type AndroidIntentProto struct {
	Action               *string                     `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	DataUri              *string                     `protobuf:"bytes,2,opt,name=dataUri" json:"dataUri,omitempty"`
	MimeType             *string                     `protobuf:"bytes,3,opt,name=mimeType" json:"mimeType,omitempty"`
	JavaClass            *string                     `protobuf:"bytes,4,opt,name=javaClass" json:"javaClass,omitempty"`
	Extra                []*AndroidIntentProto_Extra `protobuf:"group,5,rep,name=Extra,json=extra" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AndroidIntentProto) Reset()         { *m = AndroidIntentProto{} }
func (m *AndroidIntentProto) String() string { return proto.CompactTextString(m) }
func (*AndroidIntentProto) ProtoMessage()    {}
func (*AndroidIntentProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{8}
}

func (m *AndroidIntentProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidIntentProto.Unmarshal(m, b)
}
func (m *AndroidIntentProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidIntentProto.Marshal(b, m, deterministic)
}
func (m *AndroidIntentProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidIntentProto.Merge(m, src)
}
func (m *AndroidIntentProto) XXX_Size() int {
	return xxx_messageInfo_AndroidIntentProto.Size(m)
}
func (m *AndroidIntentProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidIntentProto.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidIntentProto proto.InternalMessageInfo

func (m *AndroidIntentProto) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *AndroidIntentProto) GetDataUri() string {
	if m != nil && m.DataUri != nil {
		return *m.DataUri
	}
	return ""
}

func (m *AndroidIntentProto) GetMimeType() string {
	if m != nil && m.MimeType != nil {
		return *m.MimeType
	}
	return ""
}

func (m *AndroidIntentProto) GetJavaClass() string {
	if m != nil && m.JavaClass != nil {
		return *m.JavaClass
	}
	return ""
}

func (m *AndroidIntentProto) GetExtra() []*AndroidIntentProto_Extra {
	if m != nil {
		return m.Extra
	}
	return nil
}

type AndroidIntentProto_Extra struct {
	Name                 *string  `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,7,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndroidIntentProto_Extra) Reset()         { *m = AndroidIntentProto_Extra{} }
func (m *AndroidIntentProto_Extra) String() string { return proto.CompactTextString(m) }
func (*AndroidIntentProto_Extra) ProtoMessage()    {}
func (*AndroidIntentProto_Extra) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{8, 0}
}

func (m *AndroidIntentProto_Extra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidIntentProto_Extra.Unmarshal(m, b)
}
func (m *AndroidIntentProto_Extra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidIntentProto_Extra.Marshal(b, m, deterministic)
}
func (m *AndroidIntentProto_Extra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidIntentProto_Extra.Merge(m, src)
}
func (m *AndroidIntentProto_Extra) XXX_Size() int {
	return xxx_messageInfo_AndroidIntentProto_Extra.Size(m)
}
func (m *AndroidIntentProto_Extra) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidIntentProto_Extra.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidIntentProto_Extra proto.InternalMessageInfo

func (m *AndroidIntentProto_Extra) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AndroidIntentProto_Extra) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type AndroidStatisticProto struct {
	Tag                  *string  `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Count                *int32   `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Sum                  *float32 `protobuf:"fixed32,3,opt,name=sum" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndroidStatisticProto) Reset()         { *m = AndroidStatisticProto{} }
func (m *AndroidStatisticProto) String() string { return proto.CompactTextString(m) }
func (*AndroidStatisticProto) ProtoMessage()    {}
func (*AndroidStatisticProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_530dacd488d6ff28, []int{9}
}

func (m *AndroidStatisticProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidStatisticProto.Unmarshal(m, b)
}
func (m *AndroidStatisticProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidStatisticProto.Marshal(b, m, deterministic)
}
func (m *AndroidStatisticProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidStatisticProto.Merge(m, src)
}
func (m *AndroidStatisticProto) XXX_Size() int {
	return xxx_messageInfo_AndroidStatisticProto.Size(m)
}
func (m *AndroidStatisticProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidStatisticProto.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidStatisticProto proto.InternalMessageInfo

func (m *AndroidStatisticProto) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *AndroidStatisticProto) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *AndroidStatisticProto) GetSum() float32 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*AndroidCheckinRequest)(nil), "playapi.proto.gsf.AndroidCheckinRequest")
	proto.RegisterType((*AndroidCheckinResponse)(nil), "playapi.proto.gsf.AndroidCheckinResponse")
	proto.RegisterType((*GservicesSetting)(nil), "playapi.proto.gsf.GservicesSetting")
	proto.RegisterType((*DeviceConfigurationProto)(nil), "playapi.proto.gsf.DeviceConfigurationProto")
	proto.RegisterType((*DeviceConfigurationProto_FeatureWithGLVersion)(nil), "playapi.proto.gsf.DeviceConfigurationProto.FeatureWithGLVersion")
	proto.RegisterType((*AndroidBuildProto)(nil), "playapi.proto.gsf.AndroidBuildProto")
	proto.RegisterType((*AndroidBuildProto_PackageVersion)(nil), "playapi.proto.gsf.AndroidBuildProto.PackageVersion")
	proto.RegisterType((*AndroidCheckinReasonProto)(nil), "playapi.proto.gsf.AndroidCheckinReasonProto")
	proto.RegisterType((*AndroidCheckinProto)(nil), "playapi.proto.gsf.AndroidCheckinProto")
	proto.RegisterType((*AndroidEventProto)(nil), "playapi.proto.gsf.AndroidEventProto")
	proto.RegisterType((*AndroidIntentProto)(nil), "playapi.proto.gsf.AndroidIntentProto")
	proto.RegisterType((*AndroidIntentProto_Extra)(nil), "playapi.proto.gsf.AndroidIntentProto.Extra")
	proto.RegisterType((*AndroidStatisticProto)(nil), "playapi.proto.gsf.AndroidStatisticProto")
}

func init() { proto.RegisterFile("gsf.proto", fileDescriptor_530dacd488d6ff28) }

var fileDescriptor_530dacd488d6ff28 = []byte{
	// 1732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x72, 0x1b, 0x49,
	0x15, 0x2e, 0x59, 0x96, 0x6d, 0xb5, 0x1d, 0x27, 0x19, 0x3b, 0xa9, 0x8e, 0x6b, 0x09, 0x46, 0x2c,
	0x5b, 0x2a, 0xa0, 0xb4, 0x60, 0x28, 0x2e, 0xa8, 0x5d, 0x6a, 0x1d, 0x3b, 0xc9, 0x06, 0x9c, 0x1f,
	0x5a, 0xbb, 0xa4, 0x48, 0x15, 0x17, 0xad, 0x99, 0xa3, 0x51, 0xa3, 0x99, 0x69, 0xd1, 0xdd, 0xa3,
	0x44, 0x5c, 0xf0, 0x04, 0xbc, 0x07, 0x2f, 0xc2, 0x0d, 0xaf, 0xc0, 0x03, 0xf0, 0x08, 0x5c, 0x53,
	0xe7, 0x74, 0x8f, 0x34, 0x23, 0xc9, 0x01, 0xee, 0xe6, 0x7c, 0xdd, 0xa7, 0x4f, 0x9f, 0xff, 0xd3,
	0xc3, 0xba, 0xa9, 0x1d, 0x0f, 0x66, 0x46, 0x3b, 0x1d, 0xdd, 0x9f, 0x65, 0x72, 0x21, 0x67, 0xca,
	0x93, 0x83, 0xd4, 0x8e, 0x7b, 0x7f, 0xdd, 0x67, 0x0f, 0x2e, 0x8b, 0xc4, 0x68, 0x95, 0x5c, 0x4d,
	0x20, 0x9e, 0xaa, 0x42, 0xc0, 0x9f, 0x4a, 0xb0, 0x2e, 0x8a, 0xd8, 0xae, 0xca, 0x41, 0xf1, 0xd6,
	0x79, 0xab, 0xdf, 0x15, 0xf4, 0x1d, 0x1d, 0xb3, 0x1d, 0x95, 0xf0, 0x9d, 0xf3, 0x56, 0xbf, 0x2d,
	0x76, 0x54, 0x12, 0x3d, 0x64, 0x7b, 0x89, 0x4a, 0xc1, 0x3a, 0xde, 0xa6, 0x5d, 0x81, 0x8a, 0xbe,
	0x62, 0xfb, 0xb1, 0x3f, 0x8d, 0xef, 0x9e, 0xb7, 0xfa, 0x87, 0x17, 0x9f, 0x0d, 0x36, 0x44, 0x0f,
	0x9a, 0x62, 0xdf, 0x20, 0x2e, 0x2a, 0xb6, 0xa8, 0xc7, 0x8e, 0x12, 0xb0, 0xca, 0x40, 0xf2, 0xa4,
	0x54, 0x59, 0xc2, 0x3b, 0x74, 0x7e, 0x03, 0x43, 0xe9, 0x99, 0x8e, 0x65, 0x06, 0x7c, 0xcf, 0x4b,
	0xf7, 0x54, 0xf4, 0x09, 0xeb, 0x66, 0x3a, 0x4d, 0x55, 0x91, 0xbe, 0x48, 0xf8, 0x3e, 0x5d, 0x76,
	0x05, 0x44, 0x9f, 0xb2, 0x3b, 0xb9, 0x34, 0x53, 0x70, 0x41, 0x30, 0x3f, 0x20, 0xe6, 0x26, 0x18,
	0x71, 0xb6, 0x9f, 0xcb, 0xf8, 0x32, 0x49, 0x0c, 0xef, 0x9e, 0xb7, 0xfb, 0x5d, 0x51, 0x91, 0x68,
	0x97, 0x1c, 0x54, 0xc2, 0x99, 0xb7, 0x0b, 0x7e, 0xe3, 0x99, 0x32, 0x8e, 0x75, 0x59, 0xb8, 0x2b,
	0xad, 0xa7, 0x0a, 0xf8, 0x21, 0xf1, 0x34, 0xc1, 0xe8, 0x8c, 0x1d, 0x38, 0x95, 0xc3, 0x3b, 0x5d,
	0x00, 0x3f, 0x22, 0xee, 0x25, 0x8d, 0x27, 0x58, 0x88, 0x4b, 0xa3, 0xdc, 0xe2, 0x1b, 0x3d, 0x85,
	0x82, 0xdf, 0x39, 0x6f, 0xf5, 0xf7, 0x44, 0x13, 0xc4, 0x5b, 0xcd, 0xc1, 0x58, 0xa5, 0x0b, 0x7e,
	0x7c, 0xde, 0xea, 0x77, 0x44, 0x45, 0xe2, 0x8a, 0x76, 0xf2, 0x0a, 0x8c, 0xe3, 0x77, 0xfd, 0x7d,
	0x03, 0x89, 0x96, 0xb4, 0x60, 0x94, 0xcc, 0x5e, 0x95, 0xf9, 0x08, 0x0c, 0xbf, 0xe7, 0x2d, 0x59,
	0xc7, 0xa2, 0x7b, 0xac, 0x0d, 0xb6, 0xe0, 0xf7, 0x69, 0x09, 0x3f, 0xa3, 0x3f, 0xb0, 0x93, 0x04,
	0xe6, 0x2a, 0x86, 0x2b, 0x5d, 0x8c, 0x55, 0x5a, 0x1a, 0xe9, 0x50, 0x6a, 0x44, 0xde, 0xfc, 0xd1,
	0x16, 0x6f, 0x5e, 0x6f, 0xee, 0xf6, 0x2e, 0xdd, 0x76, 0x4e, 0x74, 0xce, 0x0e, 0x83, 0x3d, 0xbf,
	0x59, 0xcc, 0x80, 0x9f, 0xd0, 0x95, 0xeb, 0x10, 0x1a, 0x6b, 0x6c, 0x64, 0x9a, 0x43, 0xe1, 0xf8,
	0x29, 0xe9, 0xba, 0xa4, 0x71, 0xad, 0xb4, 0x60, 0x5e, 0xc9, 0x1c, 0xf8, 0x03, 0x6f, 0xc8, 0x8a,
	0x8e, 0x7e, 0xc8, 0xee, 0xe1, 0xf7, 0xb0, 0xae, 0xf2, 0x43, 0xe2, 0xdf, 0xc0, 0x71, 0x2f, 0x85,
	0x60, 0x5a, 0x4a, 0x93, 0x08, 0xb0, 0x65, 0xe6, 0x38, 0xa7, 0xf3, 0x36, 0xf0, 0xe8, 0xe7, 0xec,
	0x81, 0x57, 0xe4, 0x5a, 0x3a, 0xf9, 0x3b, 0x6f, 0xf5, 0x17, 0xc5, 0x58, 0xf3, 0x47, 0xc4, 0xb0,
	0x7d, 0x31, 0x1a, 0xb0, 0x68, 0x0c, 0x2e, 0x9e, 0x0c, 0x17, 0xd6, 0x41, 0xfe, 0xed, 0x2c, 0x91,
	0x0e, 0x2c, 0xff, 0xce, 0x79, 0xab, 0x7f, 0x20, 0xb6, 0xac, 0xf4, 0xfe, 0xde, 0x66, 0x0f, 0xd7,
	0xd3, 0xd1, 0xce, 0x74, 0x61, 0x01, 0x3d, 0x6c, 0x9d, 0x74, 0xf6, 0xf5, 0x94, 0x52, 0xf2, 0x40,
	0x54, 0x64, 0xf4, 0x25, 0xdb, 0x53, 0x85, 0x43, 0x43, 0xed, 0x9c, 0xb7, 0xfb, 0x87, 0x17, 0x3f,
	0xb8, 0x3d, 0xd9, 0x5e, 0xd0, 0x3e, 0xef, 0x98, 0xc0, 0x54, 0x85, 0xe5, 0x4b, 0x0b, 0x31, 0xa5,
	0x71, 0x5b, 0x2c, 0xe9, 0x5a, 0x82, 0xef, 0x36, 0x12, 0xfc, 0x4b, 0xb6, 0x6f, 0xc1, 0x39, 0x55,
	0xa4, 0xbc, 0x43, 0x32, 0xbf, 0xbf, 0x45, 0xe6, 0x73, 0x0b, 0x06, 0x8d, 0x62, 0x87, 0x7e, 0xab,
	0xa8, 0x78, 0x50, 0xa4, 0x4f, 0xb7, 0xd7, 0x53, 0xca, 0xdd, 0x03, 0xb1, 0xa4, 0x31, 0x7b, 0x65,
	0xb8, 0xac, 0xcf, 0xde, 0x3d, 0xb1, 0x02, 0x36, 0xf3, 0xe4, 0x60, 0x5b, 0x9e, 0x50, 0xcc, 0x93,
	0x28, 0x7b, 0xad, 0xc6, 0x63, 0xde, 0x25, 0x19, 0x0d, 0x0c, 0x4f, 0x4a, 0x20, 0x03, 0x07, 0xe1,
	0x76, 0x9c, 0xf9, 0x9c, 0x6d, 0x80, 0xb7, 0xbb, 0xfd, 0xe8, 0x23, 0x6e, 0xef, 0x7d, 0xc1, 0xee,
	0xad, 0x2b, 0x8f, 0x75, 0xa3, 0xc0, 0x80, 0x45, 0xe7, 0x1d, 0x09, 0xfa, 0x8e, 0x4e, 0x59, 0x67,
	0x2e, 0xb3, 0x12, 0xa8, 0xa4, 0x1e, 0x09, 0x4f, 0xf4, 0xfe, 0x79, 0xc0, 0xf8, 0x6d, 0xe9, 0x84,
	0x99, 0xe3, 0x74, 0x19, 0x4f, 0x86, 0xb1, 0x01, 0x28, 0xe8, 0xb4, 0x8e, 0xa8, 0x43, 0x68, 0xdc,
	0x29, 0x2c, 0x46, 0x5a, 0x1a, 0x5f, 0xaa, 0x3b, 0x62, 0x49, 0x47, 0x8f, 0x19, 0x2b, 0xe4, 0x5c,
	0xa5, 0x3e, 0x9b, 0xdb, 0xb4, 0x5a, 0x43, 0xc8, 0x70, 0x74, 0xca, 0x8d, 0x5c, 0xe8, 0xd2, 0x7b,
	0xbd, 0x23, 0x1a, 0x58, 0xd4, 0x67, 0x77, 0x27, 0xd2, 0x7e, 0x2d, 0x4d, 0xf2, 0x9b, 0x4a, 0x4c,
	0x87, 0xec, 0xbb, 0x0e, 0x47, 0x17, 0xec, 0x74, 0x22, 0xed, 0x33, 0x35, 0x87, 0xb7, 0x72, 0xf1,
	0x6a, 0x25, 0xd7, 0xbb, 0x7c, 0xeb, 0x1a, 0x39, 0x98, 0xa4, 0x5d, 0x43, 0x61, 0x95, 0x5b, 0x50,
	0x08, 0x74, 0x44, 0x13, 0x44, 0x2b, 0xa4, 0xd9, 0x53, 0x1b, 0x6c, 0x4e, 0x41, 0xd0, 0x11, 0x75,
	0x28, 0xfa, 0x09, 0x3b, 0xb1, 0x94, 0x5a, 0xc3, 0x89, 0x34, 0x90, 0xdc, 0xa8, 0x91, 0x91, 0x66,
	0x11, 0x8a, 0xf9, 0xb6, 0xa5, 0xe8, 0x17, 0xec, 0xa1, 0x87, 0x2f, 0xe7, 0x52, 0x65, 0x72, 0x94,
	0xc1, 0x33, 0x90, 0xae, 0x34, 0x10, 0x22, 0xe3, 0x96, 0xd5, 0xe8, 0x33, 0x76, 0x5c, 0x48, 0xa7,
	0xe6, 0xf0, 0x26, 0x93, 0x6e, 0xac, 0x4d, 0x1e, 0xaa, 0xff, 0x1a, 0x8a, 0x77, 0xf6, 0x4a, 0xbc,
	0x55, 0x89, 0x9b, 0x50, 0x00, 0x75, 0x44, 0x1d, 0x5a, 0x59, 0xff, 0x6b, 0x50, 0xe9, 0xc4, 0x51,
	0x0f, 0x58, 0x5a, 0xdf, 0x63, 0x18, 0x90, 0xe1, 0xf2, 0xe5, 0x6c, 0xa6, 0x8d, 0x83, 0xe4, 0xc6,
	0xf7, 0xc0, 0x63, 0x12, 0xba, 0x7d, 0x31, 0xd8, 0xeb, 0x83, 0x43, 0xf3, 0xe9, 0x22, 0xb4, 0x88,
	0x3a, 0x84, 0xbe, 0xca, 0xe5, 0x87, 0xcb, 0xd9, 0xf4, 0x5a, 0xbf, 0x2f, 0x32, 0x2d, 0x93, 0xa1,
	0xfa, 0x33, 0xbc, 0x1c, 0x51, 0x4f, 0xe8, 0x88, 0xad, 0x6b, 0x74, 0x97, 0x5c, 0x66, 0x19, 0x58,
	0x37, 0x5c, 0xa9, 0x71, 0x3d, 0xa3, 0x36, 0xd1, 0x11, 0xdb, 0x17, 0x51, 0xcb, 0x4c, 0xbf, 0x17,
	0x32, 0xf7, 0x31, 0xce, 0x4f, 0x7c, 0x72, 0xd6, 0x31, 0xac, 0xcc, 0x4e, 0x3b, 0x99, 0xbd, 0x84,
	0x5c, 0x9b, 0xc5, 0x93, 0x05, 0x56, 0xcd, 0x53, 0xaa, 0x4d, 0x1b, 0x38, 0xee, 0xcd, 0xe5, 0x87,
	0x57, 0x65, 0xfe, 0x7a, 0x7c, 0x35, 0x2b, 0xaf, 0xb4, 0x01, 0x4b, 0x5d, 0xa1, 0x23, 0x36, 0xf0,
	0xe8, 0x2f, 0xec, 0x51, 0x01, 0xef, 0x87, 0xdb, 0xdd, 0x7c, 0x46, 0x95, 0xec, 0xab, 0xff, 0xa3,
	0xb9, 0x0d, 0x02, 0xeb, 0x5b, 0xe5, 0x26, 0xcf, 0x6f, 0x42, 0xe8, 0x89, 0xdb, 0x45, 0xa0, 0x95,
	0xa7, 0xb0, 0xa0, 0xbe, 0xe2, 0xcf, 0x1c, 0x62, 0xdd, 0x02, 0xfe, 0x89, 0xcf, 0x88, 0x6d, 0x6b,
	0x67, 0x37, 0xec, 0x74, 0x9b, 0x98, 0x46, 0x41, 0xe9, 0x86, 0x82, 0xb2, 0x96, 0x17, 0x3b, 0x1b,
	0x79, 0xd1, 0xfb, 0xd7, 0x2e, 0xbb, 0x1f, 0x9a, 0x01, 0x4d, 0x51, 0xbe, 0xaa, 0xf8, 0xc1, 0xce,
	0x9f, 0x84, 0x83, 0x1d, 0x67, 0xfb, 0x33, 0xa3, 0x93, 0x32, 0x76, 0x74, 0x46, 0x57, 0x54, 0x24,
	0xae, 0xc4, 0xd2, 0x18, 0x05, 0x26, 0xcc, 0x7c, 0x15, 0x89, 0xc5, 0xcc, 0xc8, 0x44, 0xe9, 0xd0,
	0x2a, 0x3c, 0x81, 0x15, 0x67, 0xa4, 0xb5, 0xc3, 0xa8, 0x01, 0x13, 0xc6, 0xb8, 0x1a, 0x82, 0x1d,
	0x26, 0xce, 0x14, 0x36, 0xaf, 0x30, 0xc4, 0x79, 0x0a, 0xdb, 0x00, 0x76, 0x21, 0xeb, 0x64, 0x3e,
	0xab, 0x86, 0xb8, 0x25, 0x80, 0x39, 0x97, 0x6a, 0x9d, 0x66, 0x30, 0x0c, 0x55, 0x36, 0x94, 0x80,
	0x35, 0x94, 0xfa, 0x97, 0x8f, 0xb2, 0x6e, 0xe8, 0x5f, 0x3e, 0xbe, 0x1e, 0x33, 0x66, 0x93, 0x69,
	0x65, 0x26, 0xe6, 0xeb, 0xe0, 0x0a, 0x41, 0x5d, 0x72, 0x9d, 0x40, 0xc6, 0x0f, 0xbd, 0x2e, 0x44,
	0x60, 0xe4, 0xe6, 0xb2, 0x28, 0xc7, 0x32, 0x46, 0x6f, 0x98, 0xd0, 0x03, 0x1a, 0x18, 0xee, 0x19,
	0x05, 0xbb, 0x92, 0xf9, 0xee, 0xf8, 0x3d, 0x75, 0x0c, 0xf7, 0x68, 0x27, 0x5f, 0x14, 0xd6, 0x61,
	0x7e, 0x24, 0x34, 0xcb, 0x1d, 0x88, 0x06, 0x16, 0xfd, 0x9e, 0xdd, 0xf1, 0xba, 0xbc, 0x91, 0xf1,
	0x54, 0xa6, 0x40, 0x39, 0x7b, 0x78, 0xf1, 0xb3, 0xdb, 0x7b, 0xfb, 0xca, 0x9d, 0x83, 0xc0, 0x53,
	0x05, 0x64, 0xf3, 0xa4, 0x7a, 0x0f, 0x7d, 0x23, 0x5d, 0x3c, 0xa1, 0x0c, 0xec, 0x8a, 0x26, 0x78,
	0xf6, 0x2b, 0x76, 0xdc, 0x3c, 0xa6, 0x3e, 0x7d, 0xb6, 0x9a, 0xd3, 0x67, 0x15, 0x8a, 0x3b, 0xab,
	0x50, 0xec, 0xfd, 0xa3, 0xc5, 0x1e, 0xad, 0x8f, 0x32, 0xd2, 0x56, 0x6d, 0xec, 0x31, 0x63, 0x86,
	0x48, 0x9a, 0xff, 0xfc, 0x71, 0x35, 0x04, 0x4d, 0x24, 0x9d, 0x83, 0x7c, 0xe6, 0xae, 0x70, 0x82,
	0x0e, 0x91, 0xdc, 0xc0, 0x48, 0x0f, 0x5d, 0x9a, 0x78, 0x69, 0xa2, 0x76, 0xd0, 0xa3, 0x0e, 0x52,
	0xd9, 0x25, 0xe0, 0x2a, 0x93, 0xd6, 0x86, 0xe0, 0xac, 0x43, 0xab, 0x1d, 0xcf, 0xb4, 0x89, 0x21,
	0x34, 0xb3, 0x3a, 0xd4, 0xfb, 0xdb, 0x2e, 0x3b, 0xd9, 0xf2, 0x5c, 0x89, 0x7e, 0xc9, 0x3a, 0xe4,
	0x58, 0x52, 0xe0, 0xf0, 0xe2, 0xd3, 0xff, 0xc5, 0x39, 0xc2, 0xb3, 0x60, 0x1b, 0xcd, 0xa4, 0xad,
	0x1e, 0x1c, 0x34, 0x7d, 0xf9, 0x87, 0xd5, 0x3a, 0x8c, 0x52, 0x60, 0x8e, 0x19, 0xd2, 0xa6, 0x10,
	0xf8, 0x88, 0x94, 0xa7, 0xf3, 0xe5, 0x74, 0xe7, 0x59, 0xa2, 0x2f, 0xd8, 0x2e, 0x8e, 0x89, 0x7c,
	0x97, 0x58, 0xfb, 0xb7, 0xb3, 0x0e, 0x9d, 0x74, 0xca, 0x3a, 0x15, 0x7b, 0x76, 0xe2, 0xc2, 0x34,
	0x33, 0xfe, 0x39, 0x08, 0xc9, 0x73, 0xa3, 0xcb, 0x19, 0x4d, 0x7b, 0x5d, 0xb1, 0x86, 0xa2, 0xb7,
	0x62, 0xc8, 0xb2, 0xd7, 0x33, 0x30, 0xd2, 0x69, 0x13, 0x52, 0xb9, 0x81, 0x91, 0x95, 0x55, 0xbe,
	0xdc, 0xb2, 0x1f, 0xfc, 0xb0, 0x82, 0x30, 0xbe, 0x8c, 0x96, 0x39, 0xce, 0x62, 0xfe, 0x4d, 0x56,
	0x91, 0x18, 0x2d, 0x34, 0xe0, 0xfb, 0x71, 0xbe, 0xeb, 0xa3, 0x65, 0x85, 0xe0, 0xba, 0x4f, 0x6c,
	0x8a, 0x26, 0xff, 0x34, 0xaa, 0x21, 0xd1, 0x35, 0xdb, 0xf3, 0xb1, 0xc5, 0xef, 0x92, 0xa3, 0x7e,
	0xfc, 0x5f, 0x9f, 0xa3, 0xb5, 0x58, 0x15, 0x81, 0x17, 0xb5, 0x9c, 0x6b, 0xec, 0x03, 0x72, 0x86,
	0x35, 0x9d, 0xba, 0xdc, 0x81, 0x68, 0x60, 0xbd, 0xb7, 0xcb, 0xea, 0xba, 0xf2, 0x05, 0x3e, 0xaf,
	0x9c, 0x4c, 0x43, 0x79, 0xc5, 0xcf, 0xe6, 0xe0, 0xd7, 0x0d, 0x83, 0xdf, 0xc7, 0x26, 0xf1, 0xde,
	0xbf, 0x5b, 0x2c, 0xda, 0x1c, 0xe2, 0xb1, 0xc0, 0xc9, 0xd8, 0x55, 0x29, 0xd9, 0x15, 0x81, 0x42,
	0x5b, 0x26, 0xd2, 0xc9, 0x6f, 0x8d, 0xaa, 0x0a, 0x78, 0x20, 0x69, 0xf6, 0x56, 0xb9, 0xb7, 0x94,
	0x4f, 0x98, 0x25, 0x8d, 0x45, 0xf7, 0x8f, 0x72, 0x2e, 0xeb, 0x99, 0xb2, 0x02, 0xa2, 0x4b, 0xd6,
	0x81, 0x0f, 0xce, 0x48, 0x0a, 0x02, 0xb6, 0xf5, 0x15, 0xb8, 0x79, 0xc3, 0xc1, 0x53, 0x64, 0x11,
	0x9e, 0xf3, 0xec, 0xa7, 0xac, 0x43, 0xf4, 0xb2, 0x62, 0xec, 0xd5, 0x9a, 0xd7, 0xd2, 0x28, 0xfb,
	0x35, 0xa3, 0xf4, 0x7e, 0xbb, 0xfc, 0x41, 0xd1, 0x0c, 0xd1, 0xed, 0x56, 0x8d, 0x6b, 0xd5, 0xc2,
	0x13, 0xb8, 0xcf, 0x96, 0x39, 0xe9, 0xba, 0x23, 0xf0, 0xf3, 0xc9, 0xf7, 0xde, 0x7d, 0x37, 0x55,
	0x6e, 0x52, 0x8e, 0x06, 0xb1, 0xce, 0x3f, 0xff, 0xb5, 0xb6, 0x93, 0x52, 0x5e, 0x6b, 0xb0, 0x9f,
	0x67, 0x6a, 0x64, 0x00, 0xb5, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xce, 0xb6, 0xe6,
	0x36, 0x11, 0x00, 0x00,
}
