// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play_respone.proto

package libplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerCommands struct {
	ClearCache           *bool                   `protobuf:"varint,1,opt,name=clearCache" json:"clearCache,omitempty"`
	DisplayErrorMessage  *string                 `protobuf:"bytes,2,opt,name=displayErrorMessage" json:"displayErrorMessage,omitempty"`
	LogErrorStacktrace   *string                 `protobuf:"bytes,3,opt,name=logErrorStacktrace" json:"logErrorStacktrace,omitempty"`
	UserSettingDirtyData []*UserSettingDirtyData `protobuf:"bytes,4,rep,name=userSettingDirtyData" json:"userSettingDirtyData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServerCommands) Reset()         { *m = ServerCommands{} }
func (m *ServerCommands) String() string { return proto.CompactTextString(m) }
func (*ServerCommands) ProtoMessage()    {}
func (*ServerCommands) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{0}
}

func (m *ServerCommands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCommands.Unmarshal(m, b)
}
func (m *ServerCommands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCommands.Marshal(b, m, deterministic)
}
func (m *ServerCommands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCommands.Merge(m, src)
}
func (m *ServerCommands) XXX_Size() int {
	return xxx_messageInfo_ServerCommands.Size(m)
}
func (m *ServerCommands) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCommands.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCommands proto.InternalMessageInfo

func (m *ServerCommands) GetClearCache() bool {
	if m != nil && m.ClearCache != nil {
		return *m.ClearCache
	}
	return false
}

func (m *ServerCommands) GetDisplayErrorMessage() string {
	if m != nil && m.DisplayErrorMessage != nil {
		return *m.DisplayErrorMessage
	}
	return ""
}

func (m *ServerCommands) GetLogErrorStacktrace() string {
	if m != nil && m.LogErrorStacktrace != nil {
		return *m.LogErrorStacktrace
	}
	return ""
}

func (m *ServerCommands) GetUserSettingDirtyData() []*UserSettingDirtyData {
	if m != nil {
		return m.UserSettingDirtyData
	}
	return nil
}

type PreFetch struct {
	Url                  *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Response             []byte   `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Etag                 *string  `protobuf:"bytes,3,opt,name=etag" json:"etag,omitempty"`
	Ttl                  *int64   `protobuf:"varint,4,opt,name=ttl" json:"ttl,omitempty"`
	SoftTtl              *int64   `protobuf:"varint,5,opt,name=softTtl" json:"softTtl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreFetch) Reset()         { *m = PreFetch{} }
func (m *PreFetch) String() string { return proto.CompactTextString(m) }
func (*PreFetch) ProtoMessage()    {}
func (*PreFetch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{1}
}

func (m *PreFetch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreFetch.Unmarshal(m, b)
}
func (m *PreFetch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreFetch.Marshal(b, m, deterministic)
}
func (m *PreFetch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreFetch.Merge(m, src)
}
func (m *PreFetch) XXX_Size() int {
	return xxx_messageInfo_PreFetch.Size(m)
}
func (m *PreFetch) XXX_DiscardUnknown() {
	xxx_messageInfo_PreFetch.DiscardUnknown(m)
}

var xxx_messageInfo_PreFetch proto.InternalMessageInfo

func (m *PreFetch) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *PreFetch) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *PreFetch) GetEtag() string {
	if m != nil && m.Etag != nil {
		return *m.Etag
	}
	return ""
}

func (m *PreFetch) GetTtl() int64 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

func (m *PreFetch) GetSoftTtl() int64 {
	if m != nil && m.SoftTtl != nil {
		return *m.SoftTtl
	}
	return 0
}

type AndroidAppNotificationData struct {
	VersionCode          *int32          `protobuf:"varint,1,opt,name=versionCode" json:"versionCode,omitempty"`
	AssetId              *string         `protobuf:"bytes,2,opt,name=assetId" json:"assetId,omitempty"`
	InstallReferrer      *string         `protobuf:"bytes,3,opt,name=installReferrer" json:"installReferrer,omitempty"`
	InstallDetails       *InstallDetails `protobuf:"bytes,4,opt,name=installDetails" json:"installDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AndroidAppNotificationData) Reset()         { *m = AndroidAppNotificationData{} }
func (m *AndroidAppNotificationData) String() string { return proto.CompactTextString(m) }
func (*AndroidAppNotificationData) ProtoMessage()    {}
func (*AndroidAppNotificationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{2}
}

func (m *AndroidAppNotificationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidAppNotificationData.Unmarshal(m, b)
}
func (m *AndroidAppNotificationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidAppNotificationData.Marshal(b, m, deterministic)
}
func (m *AndroidAppNotificationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidAppNotificationData.Merge(m, src)
}
func (m *AndroidAppNotificationData) XXX_Size() int {
	return xxx_messageInfo_AndroidAppNotificationData.Size(m)
}
func (m *AndroidAppNotificationData) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidAppNotificationData.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidAppNotificationData proto.InternalMessageInfo

func (m *AndroidAppNotificationData) GetVersionCode() int32 {
	if m != nil && m.VersionCode != nil {
		return *m.VersionCode
	}
	return 0
}

func (m *AndroidAppNotificationData) GetAssetId() string {
	if m != nil && m.AssetId != nil {
		return *m.AssetId
	}
	return ""
}

func (m *AndroidAppNotificationData) GetInstallReferrer() string {
	if m != nil && m.InstallReferrer != nil {
		return *m.InstallReferrer
	}
	return ""
}

func (m *AndroidAppNotificationData) GetInstallDetails() *InstallDetails {
	if m != nil {
		return m.InstallDetails
	}
	return nil
}

type PurchaseRemovalData struct {
	Malicious            *bool    `protobuf:"varint,1,opt,name=malicious" json:"malicious,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseRemovalData) Reset()         { *m = PurchaseRemovalData{} }
func (m *PurchaseRemovalData) String() string { return proto.CompactTextString(m) }
func (*PurchaseRemovalData) ProtoMessage()    {}
func (*PurchaseRemovalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{3}
}

func (m *PurchaseRemovalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseRemovalData.Unmarshal(m, b)
}
func (m *PurchaseRemovalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseRemovalData.Marshal(b, m, deterministic)
}
func (m *PurchaseRemovalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseRemovalData.Merge(m, src)
}
func (m *PurchaseRemovalData) XXX_Size() int {
	return xxx_messageInfo_PurchaseRemovalData.Size(m)
}
func (m *PurchaseRemovalData) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseRemovalData.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseRemovalData proto.InternalMessageInfo

func (m *PurchaseRemovalData) GetMalicious() bool {
	if m != nil && m.Malicious != nil {
		return *m.Malicious
	}
	return false
}

type UserNotificationData struct {
	NotificationTitle    *string  `protobuf:"bytes,1,opt,name=notificationTitle" json:"notificationTitle,omitempty"`
	NotificationText     *string  `protobuf:"bytes,2,opt,name=notificationText" json:"notificationText,omitempty"`
	TickerText           *string  `protobuf:"bytes,3,opt,name=tickerText" json:"tickerText,omitempty"`
	DialogTitle          *string  `protobuf:"bytes,4,opt,name=dialogTitle" json:"dialogTitle,omitempty"`
	DialogText           *string  `protobuf:"bytes,5,opt,name=dialogText" json:"dialogText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNotificationData) Reset()         { *m = UserNotificationData{} }
func (m *UserNotificationData) String() string { return proto.CompactTextString(m) }
func (*UserNotificationData) ProtoMessage()    {}
func (*UserNotificationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{4}
}

func (m *UserNotificationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotificationData.Unmarshal(m, b)
}
func (m *UserNotificationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotificationData.Marshal(b, m, deterministic)
}
func (m *UserNotificationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotificationData.Merge(m, src)
}
func (m *UserNotificationData) XXX_Size() int {
	return xxx_messageInfo_UserNotificationData.Size(m)
}
func (m *UserNotificationData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotificationData.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotificationData proto.InternalMessageInfo

func (m *UserNotificationData) GetNotificationTitle() string {
	if m != nil && m.NotificationTitle != nil {
		return *m.NotificationTitle
	}
	return ""
}

func (m *UserNotificationData) GetNotificationText() string {
	if m != nil && m.NotificationText != nil {
		return *m.NotificationText
	}
	return ""
}

func (m *UserNotificationData) GetTickerText() string {
	if m != nil && m.TickerText != nil {
		return *m.TickerText
	}
	return ""
}

func (m *UserNotificationData) GetDialogTitle() string {
	if m != nil && m.DialogTitle != nil {
		return *m.DialogTitle
	}
	return ""
}

func (m *UserNotificationData) GetDialogText() string {
	if m != nil && m.DialogText != nil {
		return *m.DialogText
	}
	return ""
}

type InAppNotificationData struct {
	CheckoutOrderId      *string  `protobuf:"bytes,1,opt,name=checkoutOrderId" json:"checkoutOrderId,omitempty"`
	InAppNotificationId  *string  `protobuf:"bytes,2,opt,name=inAppNotificationId" json:"inAppNotificationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InAppNotificationData) Reset()         { *m = InAppNotificationData{} }
func (m *InAppNotificationData) String() string { return proto.CompactTextString(m) }
func (*InAppNotificationData) ProtoMessage()    {}
func (*InAppNotificationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{5}
}

func (m *InAppNotificationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InAppNotificationData.Unmarshal(m, b)
}
func (m *InAppNotificationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InAppNotificationData.Marshal(b, m, deterministic)
}
func (m *InAppNotificationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InAppNotificationData.Merge(m, src)
}
func (m *InAppNotificationData) XXX_Size() int {
	return xxx_messageInfo_InAppNotificationData.Size(m)
}
func (m *InAppNotificationData) XXX_DiscardUnknown() {
	xxx_messageInfo_InAppNotificationData.DiscardUnknown(m)
}

var xxx_messageInfo_InAppNotificationData proto.InternalMessageInfo

func (m *InAppNotificationData) GetCheckoutOrderId() string {
	if m != nil && m.CheckoutOrderId != nil {
		return *m.CheckoutOrderId
	}
	return ""
}

func (m *InAppNotificationData) GetInAppNotificationId() string {
	if m != nil && m.InAppNotificationId != nil {
		return *m.InAppNotificationId
	}
	return ""
}

type PurchaseDeclinedData struct {
	Reason               *int32   `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
	ShowNotification     *bool    `protobuf:"varint,2,opt,name=showNotification" json:"showNotification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseDeclinedData) Reset()         { *m = PurchaseDeclinedData{} }
func (m *PurchaseDeclinedData) String() string { return proto.CompactTextString(m) }
func (*PurchaseDeclinedData) ProtoMessage()    {}
func (*PurchaseDeclinedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{6}
}

func (m *PurchaseDeclinedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseDeclinedData.Unmarshal(m, b)
}
func (m *PurchaseDeclinedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseDeclinedData.Marshal(b, m, deterministic)
}
func (m *PurchaseDeclinedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseDeclinedData.Merge(m, src)
}
func (m *PurchaseDeclinedData) XXX_Size() int {
	return xxx_messageInfo_PurchaseDeclinedData.Size(m)
}
func (m *PurchaseDeclinedData) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseDeclinedData.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseDeclinedData proto.InternalMessageInfo

func (m *PurchaseDeclinedData) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *PurchaseDeclinedData) GetShowNotification() bool {
	if m != nil && m.ShowNotification != nil {
		return *m.ShowNotification
	}
	return false
}

type LibraryDirtyData struct {
	Backend              *int32   `protobuf:"varint,1,opt,name=backend" json:"backend,omitempty"`
	LibraryId            *string  `protobuf:"bytes,2,opt,name=libraryId" json:"libraryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryDirtyData) Reset()         { *m = LibraryDirtyData{} }
func (m *LibraryDirtyData) String() string { return proto.CompactTextString(m) }
func (*LibraryDirtyData) ProtoMessage()    {}
func (*LibraryDirtyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{7}
}

func (m *LibraryDirtyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDirtyData.Unmarshal(m, b)
}
func (m *LibraryDirtyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDirtyData.Marshal(b, m, deterministic)
}
func (m *LibraryDirtyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDirtyData.Merge(m, src)
}
func (m *LibraryDirtyData) XXX_Size() int {
	return xxx_messageInfo_LibraryDirtyData.Size(m)
}
func (m *LibraryDirtyData) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDirtyData.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDirtyData proto.InternalMessageInfo

func (m *LibraryDirtyData) GetBackend() int32 {
	if m != nil && m.Backend != nil {
		return *m.Backend
	}
	return 0
}

func (m *LibraryDirtyData) GetLibraryId() string {
	if m != nil && m.LibraryId != nil {
		return *m.LibraryId
	}
	return ""
}

type Notification struct {
	NotificationType      *int32                      `protobuf:"varint,1,opt,name=notificationType" json:"notificationType,omitempty"`
	Timestamp             *int64                      `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Docid                 *Docid                      `protobuf:"bytes,4,opt,name=docid" json:"docid,omitempty"`
	DocTitle              *string                     `protobuf:"bytes,5,opt,name=docTitle" json:"docTitle,omitempty"`
	UserEmail             *string                     `protobuf:"bytes,6,opt,name=userEmail" json:"userEmail,omitempty"`
	AppData               *AndroidAppNotificationData `protobuf:"bytes,7,opt,name=appData" json:"appData,omitempty"`
	AppDeliveryData       *AndroidAppDeliveryData     `protobuf:"bytes,8,opt,name=appDeliveryData" json:"appDeliveryData,omitempty"`
	PurchaseRemovalData   *PurchaseRemovalData        `protobuf:"bytes,9,opt,name=purchaseRemovalData" json:"purchaseRemovalData,omitempty"`
	UserNotificationData  *UserNotificationData       `protobuf:"bytes,10,opt,name=userNotificationData" json:"userNotificationData,omitempty"`
	InAppNotificationData *InAppNotificationData      `protobuf:"bytes,11,opt,name=inAppNotificationData" json:"inAppNotificationData,omitempty"`
	PurchaseDeclinedData  *PurchaseDeclinedData       `protobuf:"bytes,12,opt,name=purchaseDeclinedData" json:"purchaseDeclinedData,omitempty"`
	NotificationId        *string                     `protobuf:"bytes,13,opt,name=notificationId" json:"notificationId,omitempty"`
	// TODO: optional LibraryUpdateProto.LibraryUpdate libraryUpdate = 14;
	LibraryDirtyData        *LibraryDirtyData     `protobuf:"bytes,15,opt,name=libraryDirtyData" json:"libraryDirtyData,omitempty"`
	UserSettingDirtyData    *UserSettingDirtyData `protobuf:"bytes,16,opt,name=userSettingDirtyData" json:"userSettingDirtyData,omitempty"`
	NotificationAckRequired *bool                 `protobuf:"varint,17,opt,name=notificationAckRequired" json:"notificationAckRequired,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}              `json:"-"`
	XXX_unrecognized        []byte                `json:"-"`
	XXX_sizecache           int32                 `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{8}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetNotificationType() int32 {
	if m != nil && m.NotificationType != nil {
		return *m.NotificationType
	}
	return 0
}

func (m *Notification) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Notification) GetDocid() *Docid {
	if m != nil {
		return m.Docid
	}
	return nil
}

func (m *Notification) GetDocTitle() string {
	if m != nil && m.DocTitle != nil {
		return *m.DocTitle
	}
	return ""
}

func (m *Notification) GetUserEmail() string {
	if m != nil && m.UserEmail != nil {
		return *m.UserEmail
	}
	return ""
}

func (m *Notification) GetAppData() *AndroidAppNotificationData {
	if m != nil {
		return m.AppData
	}
	return nil
}

func (m *Notification) GetAppDeliveryData() *AndroidAppDeliveryData {
	if m != nil {
		return m.AppDeliveryData
	}
	return nil
}

func (m *Notification) GetPurchaseRemovalData() *PurchaseRemovalData {
	if m != nil {
		return m.PurchaseRemovalData
	}
	return nil
}

func (m *Notification) GetUserNotificationData() *UserNotificationData {
	if m != nil {
		return m.UserNotificationData
	}
	return nil
}

func (m *Notification) GetInAppNotificationData() *InAppNotificationData {
	if m != nil {
		return m.InAppNotificationData
	}
	return nil
}

func (m *Notification) GetPurchaseDeclinedData() *PurchaseDeclinedData {
	if m != nil {
		return m.PurchaseDeclinedData
	}
	return nil
}

func (m *Notification) GetNotificationId() string {
	if m != nil && m.NotificationId != nil {
		return *m.NotificationId
	}
	return ""
}

func (m *Notification) GetLibraryDirtyData() *LibraryDirtyData {
	if m != nil {
		return m.LibraryDirtyData
	}
	return nil
}

func (m *Notification) GetUserSettingDirtyData() *UserSettingDirtyData {
	if m != nil {
		return m.UserSettingDirtyData
	}
	return nil
}

func (m *Notification) GetNotificationAckRequired() bool {
	if m != nil && m.NotificationAckRequired != nil {
		return *m.NotificationAckRequired
	}
	return false
}

type ServerMetadata struct {
	LatencyMillis        *int64   `protobuf:"varint,1,opt,name=latencyMillis" json:"latencyMillis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerMetadata) Reset()         { *m = ServerMetadata{} }
func (m *ServerMetadata) String() string { return proto.CompactTextString(m) }
func (*ServerMetadata) ProtoMessage()    {}
func (*ServerMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{9}
}

func (m *ServerMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMetadata.Unmarshal(m, b)
}
func (m *ServerMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMetadata.Marshal(b, m, deterministic)
}
func (m *ServerMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMetadata.Merge(m, src)
}
func (m *ServerMetadata) XXX_Size() int {
	return xxx_messageInfo_ServerMetadata.Size(m)
}
func (m *ServerMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMetadata proto.InternalMessageInfo

func (m *ServerMetadata) GetLatencyMillis() int64 {
	if m != nil && m.LatencyMillis != nil {
		return *m.LatencyMillis
	}
	return 0
}

type Targets struct {
	TargetId             []int64  `protobuf:"varint,1,rep,name=targetId" json:"targetId,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Targets) Reset()         { *m = Targets{} }
func (m *Targets) String() string { return proto.CompactTextString(m) }
func (*Targets) ProtoMessage()    {}
func (*Targets) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{10}
}

func (m *Targets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Targets.Unmarshal(m, b)
}
func (m *Targets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Targets.Marshal(b, m, deterministic)
}
func (m *Targets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Targets.Merge(m, src)
}
func (m *Targets) XXX_Size() int {
	return xxx_messageInfo_Targets.Size(m)
}
func (m *Targets) XXX_DiscardUnknown() {
	xxx_messageInfo_Targets.DiscardUnknown(m)
}

var xxx_messageInfo_Targets proto.InternalMessageInfo

func (m *Targets) GetTargetId() []int64 {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *Targets) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ServerCookie struct {
	Type                 *int32   `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerCookie) Reset()         { *m = ServerCookie{} }
func (m *ServerCookie) String() string { return proto.CompactTextString(m) }
func (*ServerCookie) ProtoMessage()    {}
func (*ServerCookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{11}
}

func (m *ServerCookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCookie.Unmarshal(m, b)
}
func (m *ServerCookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCookie.Marshal(b, m, deterministic)
}
func (m *ServerCookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCookie.Merge(m, src)
}
func (m *ServerCookie) XXX_Size() int {
	return xxx_messageInfo_ServerCookie.Size(m)
}
func (m *ServerCookie) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCookie.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCookie proto.InternalMessageInfo

func (m *ServerCookie) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ServerCookie) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type ServerCookies struct {
	ServerCookie         []*ServerCookie `protobuf:"bytes,1,rep,name=serverCookie" json:"serverCookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServerCookies) Reset()         { *m = ServerCookies{} }
func (m *ServerCookies) String() string { return proto.CompactTextString(m) }
func (*ServerCookies) ProtoMessage()    {}
func (*ServerCookies) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{12}
}

func (m *ServerCookies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCookies.Unmarshal(m, b)
}
func (m *ServerCookies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCookies.Marshal(b, m, deterministic)
}
func (m *ServerCookies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCookies.Merge(m, src)
}
func (m *ServerCookies) XXX_Size() int {
	return xxx_messageInfo_ServerCookies.Size(m)
}
func (m *ServerCookies) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCookies.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCookies proto.InternalMessageInfo

func (m *ServerCookies) GetServerCookie() []*ServerCookie {
	if m != nil {
		return m.ServerCookie
	}
	return nil
}

type AcceptTosResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptTosResponse) Reset()         { *m = AcceptTosResponse{} }
func (m *AcceptTosResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptTosResponse) ProtoMessage()    {}
func (*AcceptTosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{13}
}

func (m *AcceptTosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptTosResponse.Unmarshal(m, b)
}
func (m *AcceptTosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptTosResponse.Marshal(b, m, deterministic)
}
func (m *AcceptTosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptTosResponse.Merge(m, src)
}
func (m *AcceptTosResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptTosResponse.Size(m)
}
func (m *AcceptTosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptTosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptTosResponse proto.InternalMessageInfo

type Payload struct {
	DetailsResponse            *DetailsResponse            `protobuf:"bytes,2,opt,name=detailsResponse" json:"detailsResponse,omitempty"`
	SearchResponse             *SearchResponse             `protobuf:"bytes,5,opt,name=searchResponse" json:"searchResponse,omitempty"`
	TocResponse                *TocResponse                `protobuf:"bytes,6,opt,name=tocResponse" json:"tocResponse,omitempty"`
	BrowseResponse             *BrowseResponse             `protobuf:"bytes,7,opt,name=browseResponse" json:"browseResponse,omitempty"`
	BulkDetailsResponse        *BulkDetailsResponse        `protobuf:"bytes,19,opt,name=bulkDetailsResponse" json:"bulkDetailsResponse,omitempty"`
	DeliveryResponse           *DeliveryResponse           `protobuf:"bytes,21,opt,name=deliveryResponse" json:"deliveryResponse,omitempty"`
	AcceptTosResponse          *AcceptTosResponse          `protobuf:"bytes,22,opt,name=acceptTosResponse" json:"acceptTosResponse,omitempty"`
	UploadDeviceConfigResponse *UploadDeviceConfigResponse `protobuf:"bytes,28,opt,name=uploadDeviceConfigResponse" json:"uploadDeviceConfigResponse,omitempty"`
	SearchSuggestResponse      *SearchSuggestResponse      `protobuf:"bytes,40,opt,name=searchSuggestResponse" json:"searchSuggestResponse,omitempty"`
	GetUserSettingsResponse    *GetUserSettingsResponse    `protobuf:"bytes,54,opt,name=getUserSettingsResponse" json:"getUserSettingsResponse,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{14}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetDetailsResponse() *DetailsResponse {
	if m != nil {
		return m.DetailsResponse
	}
	return nil
}

func (m *Payload) GetSearchResponse() *SearchResponse {
	if m != nil {
		return m.SearchResponse
	}
	return nil
}

func (m *Payload) GetTocResponse() *TocResponse {
	if m != nil {
		return m.TocResponse
	}
	return nil
}

func (m *Payload) GetBrowseResponse() *BrowseResponse {
	if m != nil {
		return m.BrowseResponse
	}
	return nil
}

func (m *Payload) GetBulkDetailsResponse() *BulkDetailsResponse {
	if m != nil {
		return m.BulkDetailsResponse
	}
	return nil
}

func (m *Payload) GetDeliveryResponse() *DeliveryResponse {
	if m != nil {
		return m.DeliveryResponse
	}
	return nil
}

func (m *Payload) GetAcceptTosResponse() *AcceptTosResponse {
	if m != nil {
		return m.AcceptTosResponse
	}
	return nil
}

func (m *Payload) GetUploadDeviceConfigResponse() *UploadDeviceConfigResponse {
	if m != nil {
		return m.UploadDeviceConfigResponse
	}
	return nil
}

func (m *Payload) GetSearchSuggestResponse() *SearchSuggestResponse {
	if m != nil {
		return m.SearchSuggestResponse
	}
	return nil
}

func (m *Payload) GetGetUserSettingsResponse() *GetUserSettingsResponse {
	if m != nil {
		return m.GetUserSettingsResponse
	}
	return nil
}

type ResponseWrapper struct {
	Payload              *Payload        `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Commands             *ServerCommands `protobuf:"bytes,2,opt,name=commands" json:"commands,omitempty"`
	PreFetch             []*PreFetch     `protobuf:"bytes,3,rep,name=preFetch" json:"preFetch,omitempty"`
	Notification         []*Notification `protobuf:"bytes,4,rep,name=notification" json:"notification,omitempty"`
	ServerMetadata       *ServerMetadata `protobuf:"bytes,5,opt,name=serverMetadata" json:"serverMetadata,omitempty"`
	Targets              *Targets        `protobuf:"bytes,6,opt,name=targets" json:"targets,omitempty"`
	ServerCookies        *ServerCookies  `protobuf:"bytes,7,opt,name=serverCookies" json:"serverCookies,omitempty"`
	ServerLogsCookie     []byte          `protobuf:"bytes,9,opt,name=serverLogsCookie" json:"serverLogsCookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResponseWrapper) Reset()         { *m = ResponseWrapper{} }
func (m *ResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ResponseWrapper) ProtoMessage()    {}
func (*ResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f396ae11b175d40, []int{15}
}

func (m *ResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWrapper.Unmarshal(m, b)
}
func (m *ResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWrapper.Marshal(b, m, deterministic)
}
func (m *ResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWrapper.Merge(m, src)
}
func (m *ResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ResponseWrapper.Size(m)
}
func (m *ResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWrapper proto.InternalMessageInfo

func (m *ResponseWrapper) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ResponseWrapper) GetCommands() *ServerCommands {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *ResponseWrapper) GetPreFetch() []*PreFetch {
	if m != nil {
		return m.PreFetch
	}
	return nil
}

func (m *ResponseWrapper) GetNotification() []*Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *ResponseWrapper) GetServerMetadata() *ServerMetadata {
	if m != nil {
		return m.ServerMetadata
	}
	return nil
}

func (m *ResponseWrapper) GetTargets() *Targets {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ResponseWrapper) GetServerCookies() *ServerCookies {
	if m != nil {
		return m.ServerCookies
	}
	return nil
}

func (m *ResponseWrapper) GetServerLogsCookie() []byte {
	if m != nil {
		return m.ServerLogsCookie
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerCommands)(nil), "playapi.proto.finsky.response.ServerCommands")
	proto.RegisterType((*PreFetch)(nil), "playapi.proto.finsky.response.PreFetch")
	proto.RegisterType((*AndroidAppNotificationData)(nil), "playapi.proto.finsky.response.AndroidAppNotificationData")
	proto.RegisterType((*PurchaseRemovalData)(nil), "playapi.proto.finsky.response.PurchaseRemovalData")
	proto.RegisterType((*UserNotificationData)(nil), "playapi.proto.finsky.response.UserNotificationData")
	proto.RegisterType((*InAppNotificationData)(nil), "playapi.proto.finsky.response.InAppNotificationData")
	proto.RegisterType((*PurchaseDeclinedData)(nil), "playapi.proto.finsky.response.PurchaseDeclinedData")
	proto.RegisterType((*LibraryDirtyData)(nil), "playapi.proto.finsky.response.LibraryDirtyData")
	proto.RegisterType((*Notification)(nil), "playapi.proto.finsky.response.Notification")
	proto.RegisterType((*ServerMetadata)(nil), "playapi.proto.finsky.response.ServerMetadata")
	proto.RegisterType((*Targets)(nil), "playapi.proto.finsky.response.Targets")
	proto.RegisterType((*ServerCookie)(nil), "playapi.proto.finsky.response.ServerCookie")
	proto.RegisterType((*ServerCookies)(nil), "playapi.proto.finsky.response.ServerCookies")
	proto.RegisterType((*AcceptTosResponse)(nil), "playapi.proto.finsky.response.AcceptTosResponse")
	proto.RegisterType((*Payload)(nil), "playapi.proto.finsky.response.Payload")
	proto.RegisterType((*ResponseWrapper)(nil), "playapi.proto.finsky.response.ResponseWrapper")
}

func init() { proto.RegisterFile("play_respone.proto", fileDescriptor_8f396ae11b175d40) }

var fileDescriptor_8f396ae11b175d40 = []byte{
	// 1402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x5d, 0x73, 0x1b, 0x35,
	0x17, 0x9e, 0xbc, 0x4e, 0x6a, 0xe7, 0xe4, 0x5b, 0x49, 0xda, 0x9d, 0xbc, 0x05, 0xc2, 0x0e, 0x14,
	0x0f, 0x2d, 0x6e, 0x9b, 0x42, 0xa7, 0xdc, 0x30, 0xa4, 0x71, 0xe9, 0xa4, 0xd3, 0xd2, 0x8e, 0x9c,
	0x4e, 0x67, 0xca, 0x0c, 0x45, 0xd1, 0x2a, 0x6b, 0xe1, 0xf5, 0x6a, 0x91, 0xe4, 0xb4, 0xbe, 0xe1,
	0xef, 0x71, 0xc5, 0x0d, 0x5c, 0xf1, 0x5b, 0xb8, 0x61, 0xa4, 0xd5, 0xae, 0x77, 0xd7, 0x6b, 0xbb,
	0x70, 0xb7, 0x7a, 0x56, 0xe7, 0x39, 0xd2, 0xf9, 0x16, 0xa0, 0x24, 0x22, 0xe3, 0x37, 0x92, 0xa9,
	0x44, 0xc4, 0xac, 0x93, 0x48, 0xa1, 0x05, 0xfa, 0xc0, 0x60, 0x24, 0xe1, 0xe9, 0xb2, 0x73, 0xc1,
	0x63, 0x35, 0x18, 0x77, 0xd2, 0x3d, 0x8a, 0x1d, 0xec, 0x58, 0x11, 0x2a, 0x86, 0x43, 0x11, 0xa7,
	0x5b, 0x0e, 0x76, 0x2d, 0x14, 0x88, 0xb7, 0x71, 0x24, 0x48, 0x50, 0x02, 0x15, 0xd3, 0x9a, 0xc7,
	0xa1, 0x72, 0xe0, 0xa6, 0x05, 0xb5, 0xa0, 0x6e, 0xed, 0xa5, 0x92, 0xec, 0x92, 0x53, 0xf6, 0x86,
	0x8a, 0xf8, 0x82, 0x87, 0xee, 0xcf, 0x8e, 0x13, 0x27, 0x92, 0xf6, 0x4b, 0xd0, 0xb9, 0x14, 0x6f,
	0x95, 0x3b, 0xeb, 0x01, 0x72, 0xf2, 0x9a, 0xf0, 0xc8, 0xe9, 0xf0, 0xff, 0x5e, 0x82, 0xcd, 0x1e,
	0x93, 0x97, 0x4c, 0x9e, 0x88, 0xe1, 0x90, 0xc4, 0x81, 0x42, 0x1f, 0x02, 0xd0, 0x88, 0x11, 0x79,
	0x42, 0x68, 0x9f, 0x79, 0x4b, 0x87, 0x4b, 0xed, 0x16, 0x2e, 0x20, 0xe8, 0x0e, 0xec, 0x06, 0x5c,
	0x19, 0xae, 0x47, 0x52, 0x0a, 0xf9, 0x8c, 0x29, 0x45, 0x42, 0xe6, 0xfd, 0xef, 0x70, 0xa9, 0xbd,
	0x8a, 0xeb, 0x7e, 0xa1, 0x0e, 0xa0, 0x48, 0x84, 0x16, 0xea, 0x69, 0x42, 0x07, 0x5a, 0x12, 0xca,
	0xbc, 0x86, 0x15, 0xa8, 0xf9, 0x83, 0x42, 0xd8, 0x1b, 0x29, 0x26, 0x7b, 0xa9, 0x39, 0xba, 0x5c,
	0xea, 0x71, 0x97, 0x68, 0xe2, 0x2d, 0x1f, 0x36, 0xda, 0x6b, 0x47, 0xf7, 0x3a, 0xb5, 0x36, 0xcf,
	0x8d, 0xf7, 0xb2, 0x46, 0x14, 0xd7, 0x12, 0xfa, 0xef, 0xa0, 0xf5, 0x42, 0xb2, 0xef, 0x98, 0xa6,
	0x7d, 0xb4, 0x0d, 0x8d, 0x91, 0x8c, 0xec, 0x7d, 0x57, 0xb1, 0xf9, 0x44, 0x07, 0xd0, 0xca, 0x1c,
	0x69, 0x6f, 0xb7, 0x8e, 0xf3, 0x35, 0x42, 0xb0, 0xcc, 0x34, 0x09, 0xdd, 0x25, 0xec, 0xb7, 0x61,
	0xd0, 0x3a, 0xf2, 0x96, 0x0f, 0x97, 0xda, 0x0d, 0x6c, 0x3e, 0x91, 0x07, 0x4d, 0x25, 0x2e, 0xf4,
	0x99, 0x8e, 0xbc, 0x15, 0x8b, 0x66, 0x4b, 0xff, 0xaf, 0x25, 0x38, 0x38, 0x8e, 0x03, 0x29, 0x78,
	0x70, 0x9c, 0x24, 0xdf, 0x0b, 0xcd, 0x2f, 0x38, 0x25, 0x9a, 0x8b, 0xd8, 0x1c, 0x0c, 0x1d, 0xc2,
	0xda, 0x25, 0x93, 0x8a, 0x8b, 0xf8, 0x44, 0x04, 0xa9, 0x13, 0x56, 0x70, 0x11, 0x32, 0xd4, 0x44,
	0x29, 0xa6, 0x4f, 0x03, 0x67, 0xf9, 0x6c, 0x89, 0xda, 0xb0, 0xc5, 0x63, 0xa5, 0x49, 0x14, 0x61,
	0x76, 0xc1, 0xa4, 0x64, 0xd2, 0x9d, 0xb2, 0x0a, 0xa3, 0x97, 0xb0, 0xe9, 0xa0, 0x6e, 0x1a, 0x14,
	0xf6, 0xec, 0x6b, 0x47, 0x5f, 0xd4, 0x5b, 0x38, 0x8f, 0xd9, 0xd3, 0x92, 0x10, 0xae, 0x90, 0xf8,
	0xf7, 0x60, 0xf7, 0xc5, 0x48, 0xd2, 0x3e, 0x51, 0x0c, 0xb3, 0xa1, 0xb8, 0x24, 0x91, 0xbd, 0xd3,
	0x75, 0x58, 0x1d, 0x92, 0x88, 0x53, 0x2e, 0x46, 0xca, 0x85, 0xd5, 0x04, 0xf0, 0xff, 0x58, 0x82,
	0x3d, 0xe3, 0xb9, 0x29, 0x53, 0xdc, 0x82, 0x9d, 0xb8, 0x80, 0x9d, 0x71, 0x1d, 0x31, 0xe7, 0xa5,
	0xe9, 0x1f, 0xe8, 0x73, 0xd8, 0x2e, 0x81, 0xec, 0x9d, 0x76, 0xf6, 0x99, 0xc2, 0x4d, 0xa0, 0x6b,
	0x4e, 0x07, 0x4c, 0xda, 0x5d, 0xa9, 0x8d, 0x0a, 0x88, 0x71, 0x42, 0xc0, 0x49, 0x24, 0xc2, 0x54,
	0xe7, 0xb2, 0xdd, 0x50, 0x84, 0x0c, 0x83, 0x5b, 0x1a, 0x86, 0x95, 0x94, 0x61, 0x82, 0xf8, 0x0a,
	0xf6, 0x4f, 0xe3, 0x3a, 0xff, 0xb6, 0x61, 0x8b, 0xf6, 0x19, 0x1d, 0x88, 0x91, 0x7e, 0x2e, 0x03,
	0x26, 0x4f, 0x03, 0x77, 0xa5, 0x2a, 0x6c, 0xb2, 0x8d, 0x57, 0x29, 0x72, 0x9f, 0xd7, 0xfd, 0xf2,
	0x5f, 0xc3, 0x5e, 0x66, 0xfe, 0x2e, 0xa3, 0x11, 0x8f, 0x59, 0x60, 0x75, 0x5e, 0x85, 0x2b, 0x92,
	0x11, 0x25, 0x62, 0x17, 0x4e, 0x6e, 0x65, 0x4c, 0xa6, 0xfa, 0xe2, 0x6d, 0x91, 0xc5, 0xd2, 0xb7,
	0xf0, 0x14, 0xee, 0x3f, 0x81, 0xed, 0xa7, 0xfc, 0x5c, 0x12, 0x39, 0xce, 0x93, 0xc8, 0x44, 0xe2,
	0x39, 0xa1, 0x03, 0x16, 0x07, 0x8e, 0x38, 0x5b, 0x1a, 0x8f, 0x47, 0xe9, 0xee, 0xfc, 0xc4, 0x13,
	0xc0, 0xff, 0xad, 0x05, 0xeb, 0x45, 0xf2, 0x29, 0xdf, 0x8d, 0x93, 0x2c, 0xf2, 0xa7, 0x70, 0x43,
	0xad, 0xf9, 0x90, 0x29, 0x4d, 0x86, 0x89, 0x75, 0x5d, 0x03, 0x4f, 0x00, 0x74, 0x17, 0x56, 0x02,
	0x41, 0x79, 0xe0, 0xe2, 0xf9, 0xff, 0xf5, 0xf1, 0xdc, 0x35, 0x5b, 0x70, 0xba, 0xd3, 0x24, 0x7b,
	0x20, 0x68, 0xea, 0xe9, 0xd4, 0x91, 0xf9, 0xda, 0x28, 0x33, 0xe5, 0xe3, 0xd1, 0x90, 0xf0, 0xc8,
	0xbb, 0x92, 0xde, 0x23, 0x07, 0x50, 0x0f, 0x9a, 0x24, 0x49, 0x6c, 0x81, 0x6a, 0x5a, 0x75, 0x5f,
	0x77, 0xe6, 0x36, 0x85, 0xce, 0xec, 0xbc, 0xc7, 0x19, 0x13, 0x7a, 0x03, 0x5b, 0xe6, 0x93, 0x45,
	0xfc, 0x92, 0xc9, 0xb4, 0xfa, 0xb5, 0x2c, 0xf9, 0x57, 0x0b, 0x72, 0x73, 0x42, 0x5e, 0x14, 0xc6,
	0x55, 0x36, 0x14, 0xc0, 0x6e, 0x32, 0x9d, 0xa4, 0xde, 0xaa, 0x55, 0x72, 0xb4, 0xe0, 0x06, 0x35,
	0xe9, 0x8d, 0xeb, 0xe8, 0xb2, 0x4a, 0x5e, 0xbd, 0xa7, 0x07, 0x56, 0xcd, 0xbd, 0x05, 0x6a, 0xea,
	0xea, 0x01, 0xae, 0x25, 0x44, 0x3f, 0xc3, 0x3e, 0xaf, 0xcb, 0x34, 0x6f, 0xcd, 0x6a, 0xfa, 0x72,
	0x81, 0xa6, 0xda, 0x2c, 0xc5, 0xf5, 0x94, 0xe6, 0x52, 0x49, 0x4d, 0x82, 0x79, 0xeb, 0xef, 0x75,
	0xa9, 0xba, 0xdc, 0xc4, 0xb5, 0x84, 0xe8, 0x06, 0x6c, 0xc6, 0xe5, 0xb4, 0xdf, 0xb0, 0xc1, 0x57,
	0x41, 0xd1, 0x0f, 0xb0, 0x1d, 0x55, 0xb2, 0xd2, 0xdb, 0xb2, 0x87, 0xb9, 0xbd, 0xe0, 0x30, 0xd5,
	0x64, 0xc6, 0x53, 0x44, 0x33, 0x9b, 0xf1, 0xf6, 0xbc, 0xdb, 0xfe, 0x87, 0x66, 0x8c, 0x1e, 0xc0,
	0xb5, 0xe2, 0xbd, 0x8e, 0xe9, 0x00, 0xb3, 0x5f, 0x46, 0x5c, 0xb2, 0xc0, 0xdb, 0xb1, 0xe5, 0x68,
	0xd6, 0x6f, 0xff, 0x7e, 0x36, 0xc3, 0x3c, 0x63, 0x9a, 0x04, 0x86, 0xeb, 0x13, 0xd8, 0x88, 0x88,
	0x66, 0x31, 0x1d, 0x3f, 0xe3, 0x51, 0xc4, 0xd3, 0x7e, 0xd3, 0xc0, 0x65, 0xd0, 0x3f, 0x81, 0xe6,
	0x19, 0x91, 0x21, 0xd3, 0xca, 0xa4, 0xbf, 0xb6, 0x9f, 0xb6, 0x12, 0x37, 0xda, 0x0d, 0x9c, 0xaf,
	0x4d, 0xfa, 0x2b, 0x1e, 0xc6, 0x44, 0x8f, 0x64, 0x36, 0x08, 0x4c, 0x00, 0xff, 0x01, 0xac, 0x67,
	0x03, 0x94, 0x18, 0x70, 0x3b, 0x19, 0xe8, 0x49, 0xe5, 0xb2, 0xdf, 0x68, 0x0f, 0x56, 0xb4, 0x18,
	0xb0, 0xd8, 0x49, 0xa7, 0x0b, 0xff, 0x27, 0xd8, 0x28, 0x4a, 0x2a, 0xf4, 0x1c, 0xd6, 0x55, 0x01,
	0xb0, 0x07, 0x59, 0x3b, 0xba, 0xb9, 0xc0, 0x87, 0x45, 0x0e, 0x5c, 0x22, 0xf0, 0x77, 0x61, 0xe7,
	0x98, 0x52, 0x96, 0xe8, 0x33, 0xa1, 0xb0, 0xdb, 0xef, 0xff, 0xd9, 0x84, 0xe6, 0x0b, 0x32, 0x36,
	0xd5, 0x02, 0xbd, 0x82, 0x2d, 0x37, 0x0f, 0xe2, 0xe2, 0xa4, 0x33, 0x7b, 0x04, 0x70, 0xc3, 0x63,
	0xb7, 0x2c, 0x84, 0xab, 0x2c, 0xa8, 0x07, 0x9b, 0xe9, 0x38, 0x9a, 0xf3, 0xae, 0x58, 0xde, 0x9b,
	0xb3, 0xe2, 0xc5, 0x8e, 0xae, 0xbd, 0x92, 0x08, 0xae, 0x50, 0xa0, 0xc7, 0xb0, 0xa6, 0x05, 0xcd,
	0x19, 0xaf, 0x58, 0xc6, 0x4f, 0xeb, 0x19, 0xcd, 0xd8, 0x7c, 0x36, 0xd9, 0x8c, 0x8b, 0x92, 0xe6,
	0x74, 0xe9, 0x64, 0x9c, 0x73, 0x35, 0xe7, 0x9d, 0xce, 0x4d, 0xd1, 0x0f, 0x4b, 0x22, 0xb8, 0x42,
	0x81, 0x28, 0xec, 0x9e, 0x8f, 0xa2, 0x41, 0xc5, 0x34, 0xde, 0xae, 0x65, 0xbe, 0x3b, 0xdf, 0x9e,
	0x0f, 0xa7, 0x05, 0x71, 0x1d, 0x9b, 0x49, 0xf5, 0xc0, 0x95, 0xf1, 0x5c, 0xc3, 0xfe, 0xbc, 0x54,
	0xcf, 0x1b, 0x43, 0xb7, 0x22, 0x86, 0xa7, 0x88, 0xd0, 0x8f, 0xb0, 0x43, 0xaa, 0xe1, 0xe2, 0x5d,
	0xb5, 0xec, 0x77, 0x16, 0xf5, 0xb4, 0xaa, 0x1c, 0x9e, 0xa6, 0x42, 0xbf, 0xc2, 0xc1, 0x28, 0x31,
	0x87, 0xe9, 0xda, 0x37, 0xcc, 0x89, 0x7d, 0xc2, 0xe4, 0x8a, 0xae, 0x5b, 0x45, 0xdf, 0xcc, 0x32,
	0x54, 0xf1, 0xd5, 0xf3, 0x72, 0x26, 0x0b, 0x9e, 0xa3, 0x01, 0xf5, 0x61, 0x3f, 0x8d, 0xa8, 0xde,
	0x28, 0x0c, 0x99, 0xd2, 0xb9, 0xea, 0xf6, 0xbc, 0xae, 0x57, 0x8a, 0xcd, 0x8a, 0x24, 0xae, 0x27,
	0x44, 0x09, 0x5c, 0x0b, 0x99, 0x2e, 0x14, 0xbf, 0x89, 0x3d, 0xef, 0x5b, 0x5d, 0xf7, 0x17, 0xd4,
	0xcd, 0xc7, 0xf5, 0xd2, 0x78, 0x16, 0xad, 0xff, 0xfb, 0x32, 0x6c, 0x65, 0x8b, 0x57, 0x92, 0x24,
	0x09, 0x93, 0xe8, 0x5b, 0x68, 0x26, 0x69, 0xa2, 0xdb, 0x6a, 0xb4, 0x76, 0x74, 0x63, 0x51, 0x6f,
	0x4a, 0x77, 0xe3, 0x4c, 0x0c, 0x9d, 0x42, 0x8b, 0xba, 0x77, 0xe1, 0xfc, 0xc2, 0x30, 0x55, 0x8d,
	0x52, 0x21, 0x9c, 0x8b, 0xa3, 0x13, 0x68, 0x25, 0xee, 0xad, 0xe5, 0x35, 0x6c, 0x61, 0xfb, 0x6c,
	0xd1, 0x69, 0xdc, 0x76, 0x9c, 0x0b, 0x9a, 0x0a, 0x59, 0x6c, 0x02, 0xee, 0x45, 0xb8, 0xa8, 0x42,
	0x16, 0x3b, 0x38, 0x2e, 0x11, 0x98, 0x27, 0x90, 0x2a, 0xb5, 0x0e, 0x57, 0xa7, 0xde, 0xef, 0x9a,
	0x99, 0x10, 0xae, 0x90, 0x18, 0xcb, 0xa7, 0xed, 0x43, 0xb9, 0x2a, 0xb5, 0xc8, 0xf2, 0xae, 0x0f,
	0xe1, 0x4c, 0x0c, 0x61, 0xd8, 0x28, 0x96, 0x72, 0xe5, 0x2a, 0xd4, 0xad, 0x7f, 0xd1, 0x0c, 0x14,
	0x2e, 0x53, 0xd8, 0x49, 0xdf, 0x02, 0x4f, 0x45, 0xa8, 0x5c, 0x8f, 0x59, 0xb5, 0x1d, 0x69, 0x0a,
	0x7f, 0xf8, 0xf1, 0xeb, 0x8f, 0x42, 0xae, 0xfb, 0xa3, 0xf3, 0x0e, 0x15, 0xc3, 0xdb, 0x4f, 0x84,
	0xea, 0x8f, 0x48, 0x57, 0x30, 0x75, 0xdb, 0x0c, 0x08, 0xcc, 0x1c, 0xe2, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x74, 0xa6, 0xdb, 0x10, 0x11, 0x00, 0x00,
}
