// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play_link.proto

package libplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Link struct {
	Uri                  *string       `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	ResolvedLink         *ResolvedLink `protobuf:"bytes,2,opt,name=resolvedLink" json:"resolvedLink,omitempty"`
	UriBackend           *int32        `protobuf:"varint,3,opt,name=uriBackend" json:"uriBackend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_77fe102278ea7940, []int{0}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Link) GetResolvedLink() *ResolvedLink {
	if m != nil {
		return m.ResolvedLink
	}
	return nil
}

func (m *Link) GetUriBackend() int32 {
	if m != nil && m.UriBackend != nil {
		return *m.UriBackend
	}
	return 0
}

type OverflowLink struct {
	Title                *string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Link                 *Link    `protobuf:"bytes,2,opt,name=link" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OverflowLink) Reset()         { *m = OverflowLink{} }
func (m *OverflowLink) String() string { return proto.CompactTextString(m) }
func (*OverflowLink) ProtoMessage()    {}
func (*OverflowLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_77fe102278ea7940, []int{1}
}

func (m *OverflowLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OverflowLink.Unmarshal(m, b)
}
func (m *OverflowLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OverflowLink.Marshal(b, m, deterministic)
}
func (m *OverflowLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OverflowLink.Merge(m, src)
}
func (m *OverflowLink) XXX_Size() int {
	return xxx_messageInfo_OverflowLink.Size(m)
}
func (m *OverflowLink) XXX_DiscardUnknown() {
	xxx_messageInfo_OverflowLink.DiscardUnknown(m)
}

var xxx_messageInfo_OverflowLink proto.InternalMessageInfo

func (m *OverflowLink) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *OverflowLink) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

type DirectPurchase struct {
	DetailsUrl           *string  `protobuf:"bytes,1,opt,name=detailsUrl" json:"detailsUrl,omitempty"`
	PurchaseDocid        *string  `protobuf:"bytes,2,opt,name=purchaseDocid" json:"purchaseDocid,omitempty"`
	ParentDocid          *string  `protobuf:"bytes,3,opt,name=parentDocid" json:"parentDocid,omitempty"`
	OfferType            *int32   `protobuf:"varint,4,opt,name=offerType" json:"offerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectPurchase) Reset()         { *m = DirectPurchase{} }
func (m *DirectPurchase) String() string { return proto.CompactTextString(m) }
func (*DirectPurchase) ProtoMessage()    {}
func (*DirectPurchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_77fe102278ea7940, []int{2}
}

func (m *DirectPurchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectPurchase.Unmarshal(m, b)
}
func (m *DirectPurchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectPurchase.Marshal(b, m, deterministic)
}
func (m *DirectPurchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectPurchase.Merge(m, src)
}
func (m *DirectPurchase) XXX_Size() int {
	return xxx_messageInfo_DirectPurchase.Size(m)
}
func (m *DirectPurchase) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectPurchase.DiscardUnknown(m)
}

var xxx_messageInfo_DirectPurchase proto.InternalMessageInfo

func (m *DirectPurchase) GetDetailsUrl() string {
	if m != nil && m.DetailsUrl != nil {
		return *m.DetailsUrl
	}
	return ""
}

func (m *DirectPurchase) GetPurchaseDocid() string {
	if m != nil && m.PurchaseDocid != nil {
		return *m.PurchaseDocid
	}
	return ""
}

func (m *DirectPurchase) GetParentDocid() string {
	if m != nil && m.ParentDocid != nil {
		return *m.ParentDocid
	}
	return ""
}

func (m *DirectPurchase) GetOfferType() int32 {
	if m != nil && m.OfferType != nil {
		return *m.OfferType
	}
	return 0
}

type HelpCenter struct {
	ContextId            *string  `protobuf:"bytes,1,opt,name=contextId" json:"contextId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelpCenter) Reset()         { *m = HelpCenter{} }
func (m *HelpCenter) String() string { return proto.CompactTextString(m) }
func (*HelpCenter) ProtoMessage()    {}
func (*HelpCenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_77fe102278ea7940, []int{3}
}

func (m *HelpCenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelpCenter.Unmarshal(m, b)
}
func (m *HelpCenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelpCenter.Marshal(b, m, deterministic)
}
func (m *HelpCenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelpCenter.Merge(m, src)
}
func (m *HelpCenter) XXX_Size() int {
	return xxx_messageInfo_HelpCenter.Size(m)
}
func (m *HelpCenter) XXX_DiscardUnknown() {
	xxx_messageInfo_HelpCenter.DiscardUnknown(m)
}

var xxx_messageInfo_HelpCenter proto.InternalMessageInfo

func (m *HelpCenter) GetContextId() string {
	if m != nil && m.ContextId != nil {
		return *m.ContextId
	}
	return ""
}

type RedeemGiftCard struct {
	PrefillCode          *string  `protobuf:"bytes,1,opt,name=prefillCode" json:"prefillCode,omitempty"`
	PartnerPayload       *string  `protobuf:"bytes,2,opt,name=partnerPayload" json:"partnerPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemGiftCard) Reset()         { *m = RedeemGiftCard{} }
func (m *RedeemGiftCard) String() string { return proto.CompactTextString(m) }
func (*RedeemGiftCard) ProtoMessage()    {}
func (*RedeemGiftCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_77fe102278ea7940, []int{4}
}

func (m *RedeemGiftCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemGiftCard.Unmarshal(m, b)
}
func (m *RedeemGiftCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemGiftCard.Marshal(b, m, deterministic)
}
func (m *RedeemGiftCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemGiftCard.Merge(m, src)
}
func (m *RedeemGiftCard) XXX_Size() int {
	return xxx_messageInfo_RedeemGiftCard.Size(m)
}
func (m *RedeemGiftCard) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemGiftCard.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemGiftCard proto.InternalMessageInfo

func (m *RedeemGiftCard) GetPrefillCode() string {
	if m != nil && m.PrefillCode != nil {
		return *m.PrefillCode
	}
	return ""
}

func (m *RedeemGiftCard) GetPartnerPayload() string {
	if m != nil && m.PartnerPayload != nil {
		return *m.PartnerPayload
	}
	return ""
}

type ResolvedLink struct {
	DetailsUrl           *string         `protobuf:"bytes,1,opt,name=detailsUrl" json:"detailsUrl,omitempty"`
	BrowseUrl            *string         `protobuf:"bytes,2,opt,name=browseUrl" json:"browseUrl,omitempty"`
	SearchUrl            *string         `protobuf:"bytes,3,opt,name=searchUrl" json:"searchUrl,omitempty"`
	DirectPurchase       *DirectPurchase `protobuf:"bytes,4,opt,name=directPurchase" json:"directPurchase,omitempty"`
	HomeUrl              *string         `protobuf:"bytes,5,opt,name=homeUrl" json:"homeUrl,omitempty"`
	RedeemGiftCard       *RedeemGiftCard `protobuf:"bytes,6,opt,name=redeemGiftCard" json:"redeemGiftCard,omitempty"`
	ServerLogsCookie     []byte          `protobuf:"bytes,7,opt,name=serverLogsCookie" json:"serverLogsCookie,omitempty"`
	Docid                *Docid          `protobuf:"bytes,8,opt,name=docid" json:"docid,omitempty"`
	WishlistUrl          *string         `protobuf:"bytes,9,opt,name=wishlistUrl" json:"wishlistUrl,omitempty"`
	Backend              *int32          `protobuf:"varint,10,opt,name=backend" json:"backend,omitempty"`
	Query                *string         `protobuf:"bytes,11,opt,name=query" json:"query,omitempty"`
	MyAccountUrl         *string         `protobuf:"bytes,12,opt,name=myAccountUrl" json:"myAccountUrl,omitempty"`
	HelpCenter           *HelpCenter     `protobuf:"bytes,13,opt,name=helpCenter" json:"helpCenter,omitempty"`
	GiftUrl              *string         `protobuf:"bytes,14,opt,name=giftUrl" json:"giftUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResolvedLink) Reset()         { *m = ResolvedLink{} }
func (m *ResolvedLink) String() string { return proto.CompactTextString(m) }
func (*ResolvedLink) ProtoMessage()    {}
func (*ResolvedLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_77fe102278ea7940, []int{5}
}

func (m *ResolvedLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedLink.Unmarshal(m, b)
}
func (m *ResolvedLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedLink.Marshal(b, m, deterministic)
}
func (m *ResolvedLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedLink.Merge(m, src)
}
func (m *ResolvedLink) XXX_Size() int {
	return xxx_messageInfo_ResolvedLink.Size(m)
}
func (m *ResolvedLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedLink.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedLink proto.InternalMessageInfo

func (m *ResolvedLink) GetDetailsUrl() string {
	if m != nil && m.DetailsUrl != nil {
		return *m.DetailsUrl
	}
	return ""
}

func (m *ResolvedLink) GetBrowseUrl() string {
	if m != nil && m.BrowseUrl != nil {
		return *m.BrowseUrl
	}
	return ""
}

func (m *ResolvedLink) GetSearchUrl() string {
	if m != nil && m.SearchUrl != nil {
		return *m.SearchUrl
	}
	return ""
}

func (m *ResolvedLink) GetDirectPurchase() *DirectPurchase {
	if m != nil {
		return m.DirectPurchase
	}
	return nil
}

func (m *ResolvedLink) GetHomeUrl() string {
	if m != nil && m.HomeUrl != nil {
		return *m.HomeUrl
	}
	return ""
}

func (m *ResolvedLink) GetRedeemGiftCard() *RedeemGiftCard {
	if m != nil {
		return m.RedeemGiftCard
	}
	return nil
}

func (m *ResolvedLink) GetServerLogsCookie() []byte {
	if m != nil {
		return m.ServerLogsCookie
	}
	return nil
}

func (m *ResolvedLink) GetDocid() *Docid {
	if m != nil {
		return m.Docid
	}
	return nil
}

func (m *ResolvedLink) GetWishlistUrl() string {
	if m != nil && m.WishlistUrl != nil {
		return *m.WishlistUrl
	}
	return ""
}

func (m *ResolvedLink) GetBackend() int32 {
	if m != nil && m.Backend != nil {
		return *m.Backend
	}
	return 0
}

func (m *ResolvedLink) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *ResolvedLink) GetMyAccountUrl() string {
	if m != nil && m.MyAccountUrl != nil {
		return *m.MyAccountUrl
	}
	return ""
}

func (m *ResolvedLink) GetHelpCenter() *HelpCenter {
	if m != nil {
		return m.HelpCenter
	}
	return nil
}

func (m *ResolvedLink) GetGiftUrl() string {
	if m != nil && m.GiftUrl != nil {
		return *m.GiftUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Link)(nil), "playapi.proto.finsky.link.Link")
	proto.RegisterType((*OverflowLink)(nil), "playapi.proto.finsky.link.OverflowLink")
	proto.RegisterType((*DirectPurchase)(nil), "playapi.proto.finsky.link.DirectPurchase")
	proto.RegisterType((*HelpCenter)(nil), "playapi.proto.finsky.link.HelpCenter")
	proto.RegisterType((*RedeemGiftCard)(nil), "playapi.proto.finsky.link.RedeemGiftCard")
	proto.RegisterType((*ResolvedLink)(nil), "playapi.proto.finsky.link.ResolvedLink")
}

func init() { proto.RegisterFile("play_link.proto", fileDescriptor_77fe102278ea7940) }

var fileDescriptor_77fe102278ea7940 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdb, 0x72, 0xd3, 0x30,
	0x10, 0x1d, 0xd3, 0x84, 0x92, 0x4d, 0x1a, 0x8a, 0x86, 0x07, 0x03, 0x1d, 0x1a, 0x3c, 0x5c, 0x42,
	0x1f, 0xd2, 0xa1, 0x7c, 0x01, 0x4d, 0x19, 0x6e, 0x9d, 0xa1, 0x68, 0xe0, 0x81, 0xbe, 0x30, 0x8a,
	0xbd, 0xae, 0x35, 0x91, 0x2d, 0x23, 0xc9, 0x2d, 0xfe, 0x00, 0x7e, 0x81, 0xef, 0xe3, 0x53, 0x18,
	0xc9, 0x0e, 0xb6, 0x03, 0x84, 0x37, 0xef, 0xd9, 0xe3, 0x3d, 0x67, 0x2f, 0x82, 0x9b, 0xb9, 0x60,
	0xe5, 0x17, 0xc1, 0xb3, 0xe5, 0x2c, 0x57, 0xd2, 0x48, 0x72, 0xc7, 0x02, 0x2c, 0xe7, 0x55, 0x38,
	0x8b, 0x79, 0xa6, 0x97, 0xe5, 0xcc, 0x12, 0xee, 0xde, 0x72, 0xdc, 0x50, 0xa6, 0xa9, 0xcc, 0xaa,
	0x74, 0xf0, 0xdd, 0x83, 0xde, 0x29, 0xcf, 0x96, 0x64, 0x17, 0xb6, 0x0a, 0xc5, 0x7d, 0x6f, 0xe2,
	0x4d, 0x07, 0xd4, 0x7e, 0x92, 0x77, 0x30, 0x52, 0xa8, 0xa5, 0xb8, 0xc4, 0xc8, 0x32, 0xfc, 0x6b,
	0x13, 0x6f, 0x3a, 0x3c, 0x7a, 0x32, 0xfb, 0x67, 0xfd, 0x19, 0x6d, 0xd1, 0x69, 0xe7, 0x67, 0x72,
	0x1f, 0xa0, 0x50, 0xfc, 0x98, 0x85, 0x4b, 0xcc, 0x22, 0x7f, 0x6b, 0xe2, 0x4d, 0xfb, 0xb4, 0x85,
	0x04, 0x9f, 0x61, 0xf4, 0xfe, 0x12, 0x55, 0x2c, 0xe4, 0x95, 0xe3, 0xdf, 0x86, 0xbe, 0xe1, 0x46,
	0x60, 0x6d, 0xa8, 0x0a, 0xc8, 0x73, 0xe8, 0x89, 0xc6, 0xca, 0xfe, 0x06, 0x2b, 0xce, 0x82, 0x23,
	0x07, 0x3f, 0x3c, 0x18, 0x9f, 0x70, 0x85, 0xa1, 0x39, 0x2b, 0x54, 0x98, 0x30, 0x8d, 0xd6, 0x4d,
	0x84, 0x86, 0x71, 0xa1, 0x3f, 0x29, 0x51, 0x4b, 0xb4, 0x10, 0xf2, 0x10, 0x76, 0xf2, 0x9a, 0x7b,
	0x22, 0x43, 0x1e, 0x39, 0xc1, 0x01, 0xed, 0x82, 0x64, 0x02, 0xc3, 0x9c, 0x29, 0xcc, 0x4c, 0xc5,
	0xd9, 0x72, 0x9c, 0x36, 0x44, 0xf6, 0x60, 0x20, 0xe3, 0x18, 0xd5, 0xc7, 0x32, 0x47, 0xbf, 0xe7,
	0x9a, 0x6e, 0x80, 0xe0, 0x00, 0xe0, 0x35, 0x8a, 0x7c, 0x8e, 0x99, 0x41, 0x65, 0xb9, 0xa1, 0xcc,
	0x0c, 0x7e, 0x33, 0x6f, 0xa2, 0xda, 0x52, 0x03, 0x04, 0xe7, 0x30, 0xa6, 0x18, 0x21, 0xa6, 0xaf,
	0x78, 0x6c, 0xe6, 0x4c, 0x55, 0xea, 0x0a, 0x63, 0x2e, 0xc4, 0x5c, 0x46, 0xab, 0x39, 0xb5, 0x21,
	0xf2, 0x18, 0xc6, 0x39, 0x53, 0x26, 0x43, 0x75, 0xc6, 0x4a, 0x21, 0xd9, 0xaa, 0x8d, 0x35, 0x34,
	0xf8, 0xd9, 0x83, 0x11, 0x5d, 0x5b, 0xd6, 0xc6, 0xf1, 0xec, 0xc1, 0x60, 0xa1, 0xe4, 0x95, 0x46,
	0x9b, 0xae, 0x6a, 0x36, 0x80, 0xcd, 0x6a, 0x64, 0x2a, 0x4c, 0x6c, 0xb6, 0x1a, 0x4a, 0x03, 0x90,
	0x0f, 0x30, 0x8e, 0x3a, 0xcb, 0x70, 0x73, 0x19, 0x1e, 0x3d, 0xdd, 0xb0, 0xcc, 0xee, 0xf6, 0xe8,
	0x5a, 0x01, 0xe2, 0xc3, 0x76, 0x22, 0x53, 0x67, 0xa6, 0xef, 0xe4, 0x56, 0xa1, 0x15, 0x53, 0x9d,
	0xa9, 0xf9, 0xd7, 0xff, 0x2b, 0xd6, 0x1d, 0x33, 0x5d, 0x2b, 0x40, 0x0e, 0x60, 0x57, 0xa3, 0xba,
	0x44, 0x75, 0x2a, 0x2f, 0xf4, 0x5c, 0xca, 0x25, 0x47, 0x7f, 0x7b, 0xe2, 0x4d, 0x47, 0xf4, 0x0f,
	0x9c, 0x3c, 0x83, 0x7e, 0xe4, 0x4e, 0xe3, 0x86, 0x53, 0xbd, 0xf7, 0x77, 0x55, 0x77, 0x2a, 0xb4,
	0x62, 0xda, 0xad, 0x5e, 0x71, 0x9d, 0x08, 0xae, 0x8d, 0xed, 0x67, 0x50, 0x6d, 0xb5, 0x05, 0xd9,
	0x6e, 0x17, 0xf5, 0x33, 0x02, 0x77, 0x51, 0xab, 0xd0, 0xbe, 0x99, 0xaf, 0x05, 0xaa, 0xd2, 0x1f,
	0x56, 0x6f, 0xc6, 0x05, 0x24, 0x80, 0x51, 0x5a, 0xbe, 0x08, 0x43, 0x59, 0x64, 0xae, 0xe4, 0xc8,
	0x25, 0x3b, 0x18, 0x79, 0x09, 0x90, 0xfc, 0xbe, 0x44, 0x7f, 0xc7, 0xb9, 0x7d, 0xb4, 0x61, 0x46,
	0xcd, 0xd9, 0xd2, 0xd6, 0x8f, 0xd6, 0xda, 0x05, 0x8f, 0x9d, 0xca, 0xb8, 0x5a, 0x44, 0x1d, 0x1e,
	0x3f, 0x38, 0xdf, 0xbf, 0xe0, 0x26, 0x29, 0x16, 0xb3, 0x50, 0xa6, 0x87, 0x6f, 0xa5, 0x4e, 0x0a,
	0x76, 0x22, 0x51, 0x1f, 0x0a, 0xbe, 0x50, 0x68, 0x85, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd5,
	0x1d, 0x58, 0x0f, 0xc9, 0x04, 0x00, 0x00,
}
