// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play_device_config.proto

package libplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MobileSubscriber struct {
	Imsi                 *int64   `protobuf:"varint,1,opt,name=imsi" json:"imsi,omitempty"`
	Spn                  *string  `protobuf:"bytes,2,opt,name=spn" json:"spn,omitempty"`
	Gid1                 *string  `protobuf:"bytes,3,opt,name=gid1" json:"gid1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileSubscriber) Reset()         { *m = MobileSubscriber{} }
func (m *MobileSubscriber) String() string { return proto.CompactTextString(m) }
func (*MobileSubscriber) ProtoMessage()    {}
func (*MobileSubscriber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539dd4e784e75df, []int{0}
}

func (m *MobileSubscriber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileSubscriber.Unmarshal(m, b)
}
func (m *MobileSubscriber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileSubscriber.Marshal(b, m, deterministic)
}
func (m *MobileSubscriber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileSubscriber.Merge(m, src)
}
func (m *MobileSubscriber) XXX_Size() int {
	return xxx_messageInfo_MobileSubscriber.Size(m)
}
func (m *MobileSubscriber) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileSubscriber.DiscardUnknown(m)
}

var xxx_messageInfo_MobileSubscriber proto.InternalMessageInfo

func (m *MobileSubscriber) GetImsi() int64 {
	if m != nil && m.Imsi != nil {
		return *m.Imsi
	}
	return 0
}

func (m *MobileSubscriber) GetSpn() string {
	if m != nil && m.Spn != nil {
		return *m.Spn
	}
	return ""
}

func (m *MobileSubscriber) GetGid1() string {
	if m != nil && m.Gid1 != nil {
		return *m.Gid1
	}
	return ""
}

type DataServiceSubscriber struct {
	MobileSubscriber     *MobileSubscriber `protobuf:"bytes,1,opt,name=mobileSubscriber" json:"mobileSubscriber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataServiceSubscriber) Reset()         { *m = DataServiceSubscriber{} }
func (m *DataServiceSubscriber) String() string { return proto.CompactTextString(m) }
func (*DataServiceSubscriber) ProtoMessage()    {}
func (*DataServiceSubscriber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539dd4e784e75df, []int{1}
}

func (m *DataServiceSubscriber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataServiceSubscriber.Unmarshal(m, b)
}
func (m *DataServiceSubscriber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataServiceSubscriber.Marshal(b, m, deterministic)
}
func (m *DataServiceSubscriber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataServiceSubscriber.Merge(m, src)
}
func (m *DataServiceSubscriber) XXX_Size() int {
	return xxx_messageInfo_DataServiceSubscriber.Size(m)
}
func (m *DataServiceSubscriber) XXX_DiscardUnknown() {
	xxx_messageInfo_DataServiceSubscriber.DiscardUnknown(m)
}

var xxx_messageInfo_DataServiceSubscriber proto.InternalMessageInfo

func (m *DataServiceSubscriber) GetMobileSubscriber() *MobileSubscriber {
	if m != nil {
		return m.MobileSubscriber
	}
	return nil
}

type UploadDeviceConfigRequest struct {
	DeviceConfiguration   *DeviceConfigurationProto `protobuf:"bytes,1,opt,name=deviceConfiguration" json:"deviceConfiguration,omitempty"`
	Manufacturer          *string                   `protobuf:"bytes,2,opt,name=manufacturer" json:"manufacturer,omitempty"`
	GcmRegistrationId     *string                   `protobuf:"bytes,3,opt,name=gcmRegistrationId" json:"gcmRegistrationId,omitempty"`
	DataServiceSubscriber *DataServiceSubscriber    `protobuf:"bytes,4,opt,name=dataServiceSubscriber" json:"dataServiceSubscriber,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *UploadDeviceConfigRequest) Reset()         { *m = UploadDeviceConfigRequest{} }
func (m *UploadDeviceConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UploadDeviceConfigRequest) ProtoMessage()    {}
func (*UploadDeviceConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539dd4e784e75df, []int{2}
}

func (m *UploadDeviceConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadDeviceConfigRequest.Unmarshal(m, b)
}
func (m *UploadDeviceConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadDeviceConfigRequest.Marshal(b, m, deterministic)
}
func (m *UploadDeviceConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadDeviceConfigRequest.Merge(m, src)
}
func (m *UploadDeviceConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UploadDeviceConfigRequest.Size(m)
}
func (m *UploadDeviceConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadDeviceConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadDeviceConfigRequest proto.InternalMessageInfo

func (m *UploadDeviceConfigRequest) GetDeviceConfiguration() *DeviceConfigurationProto {
	if m != nil {
		return m.DeviceConfiguration
	}
	return nil
}

func (m *UploadDeviceConfigRequest) GetManufacturer() string {
	if m != nil && m.Manufacturer != nil {
		return *m.Manufacturer
	}
	return ""
}

func (m *UploadDeviceConfigRequest) GetGcmRegistrationId() string {
	if m != nil && m.GcmRegistrationId != nil {
		return *m.GcmRegistrationId
	}
	return ""
}

func (m *UploadDeviceConfigRequest) GetDataServiceSubscriber() *DataServiceSubscriber {
	if m != nil {
		return m.DataServiceSubscriber
	}
	return nil
}

type UploadDeviceConfigResponse struct {
	UploadDeviceConfigToken *string  `protobuf:"bytes,1,opt,name=uploadDeviceConfigToken" json:"uploadDeviceConfigToken,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *UploadDeviceConfigResponse) Reset()         { *m = UploadDeviceConfigResponse{} }
func (m *UploadDeviceConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UploadDeviceConfigResponse) ProtoMessage()    {}
func (*UploadDeviceConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539dd4e784e75df, []int{3}
}

func (m *UploadDeviceConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadDeviceConfigResponse.Unmarshal(m, b)
}
func (m *UploadDeviceConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadDeviceConfigResponse.Marshal(b, m, deterministic)
}
func (m *UploadDeviceConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadDeviceConfigResponse.Merge(m, src)
}
func (m *UploadDeviceConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UploadDeviceConfigResponse.Size(m)
}
func (m *UploadDeviceConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadDeviceConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadDeviceConfigResponse proto.InternalMessageInfo

func (m *UploadDeviceConfigResponse) GetUploadDeviceConfigToken() string {
	if m != nil && m.UploadDeviceConfigToken != nil {
		return *m.UploadDeviceConfigToken
	}
	return ""
}

func init() {
	proto.RegisterType((*MobileSubscriber)(nil), "playapi.proto.finsky.device_config.MobileSubscriber")
	proto.RegisterType((*DataServiceSubscriber)(nil), "playapi.proto.finsky.device_config.DataServiceSubscriber")
	proto.RegisterType((*UploadDeviceConfigRequest)(nil), "playapi.proto.finsky.device_config.UploadDeviceConfigRequest")
	proto.RegisterType((*UploadDeviceConfigResponse)(nil), "playapi.proto.finsky.device_config.UploadDeviceConfigResponse")
}

func init() { proto.RegisterFile("play_device_config.proto", fileDescriptor_1539dd4e784e75df) }

var fileDescriptor_1539dd4e784e75df = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xd5, 0x3f, 0x4b, 0x0d, 0x43, 0x6b, 0x54, 0x11, 0xba, 0x50, 0x32, 0x55, 0x02, 0xa5,
	0x02, 0x31, 0xc0, 0x0a, 0x59, 0x40, 0x20, 0x21, 0x17, 0x18, 0x90, 0x50, 0x71, 0x12, 0x27, 0xb5,
	0x9a, 0xf8, 0x82, 0xff, 0x20, 0xf5, 0xc3, 0xf1, 0xdd, 0x90, 0x9d, 0x0e, 0x6d, 0x13, 0x04, 0xdb,
	0xe5, 0xde, 0xdd, 0xcb, 0xbb, 0x9f, 0x91, 0x57, 0xe6, 0x74, 0x35, 0x4f, 0xd8, 0x17, 0x8f, 0xd9,
	0x3c, 0x06, 0x91, 0xf2, 0x2c, 0x28, 0x25, 0x68, 0xc0, 0xbe, 0x55, 0x68, 0xc9, 0xab, 0xcf, 0x20,
	0xe5, 0x42, 0x2d, 0x57, 0xc1, 0xd6, 0xe4, 0xa8, 0x97, 0xa9, 0xb4, 0xd2, 0x47, 0x03, 0x67, 0x14,
	0x43, 0x51, 0x80, 0xa8, 0x5a, 0xfe, 0x03, 0xea, 0x3f, 0x42, 0xc4, 0x73, 0x36, 0x33, 0x91, 0x8a,
	0x25, 0x8f, 0x98, 0xc4, 0x18, 0x75, 0x79, 0xa1, 0xb8, 0xd7, 0x1a, 0xb7, 0x26, 0x1d, 0xe2, 0x6a,
	0xdc, 0x47, 0x1d, 0x55, 0x0a, 0xaf, 0x3d, 0x6e, 0x4d, 0x7a, 0xc4, 0x96, 0x76, 0x2a, 0xe3, 0xc9,
	0xb9, 0xd7, 0x71, 0x2d, 0x57, 0xfb, 0x2b, 0x34, 0x0c, 0xa9, 0xa6, 0x33, 0x26, 0x6d, 0x82, 0x0d,
	0xcb, 0x0f, 0xd4, 0x2f, 0x76, 0x7e, 0xe3, 0xec, 0xf7, 0x2e, 0x2e, 0x83, 0xbf, 0x6f, 0x08, 0x76,
	0x23, 0x92, 0x9a, 0x9b, 0xff, 0xdd, 0x46, 0x47, 0x2f, 0x65, 0x0e, 0x34, 0x09, 0xdd, 0xea, 0xad,
	0xdb, 0x24, 0xec, 0xd3, 0x30, 0xa5, 0xf1, 0x3b, 0x3a, 0x48, 0x36, 0xda, 0x46, 0x52, 0xcd, 0x41,
	0xac, 0x23, 0x9c, 0xee, 0x44, 0xb0, 0xc0, 0xc2, 0xfa, 0xf4, 0x93, 0x15, 0x49, 0x93, 0x0f, 0xf6,
	0xd1, 0x7e, 0x41, 0x85, 0x49, 0x69, 0xac, 0x8d, 0x64, 0x72, 0x8d, 0x69, 0xab, 0x87, 0xcf, 0xd0,
	0x20, 0x8b, 0x0b, 0xc2, 0x32, 0xae, 0x74, 0xb5, 0x76, 0x97, 0xac, 0xe1, 0xd5, 0x05, 0x0c, 0x68,
	0x98, 0x34, 0x91, 0xf4, 0xba, 0x2e, 0xf2, 0xf5, 0x7f, 0xa8, 0x35, 0x3e, 0x05, 0x69, 0xf6, 0xf5,
	0x5f, 0xd1, 0xa8, 0x09, 0x9f, 0x2a, 0x41, 0x28, 0x86, 0xaf, 0xd0, 0xa1, 0xa9, 0xa9, 0xcf, 0xb0,
	0x64, 0x15, 0xc3, 0x1e, 0xf9, 0x4d, 0xbe, 0x39, 0x79, 0x3b, 0xce, 0xb8, 0x5e, 0x98, 0x28, 0x88,
	0xa1, 0x98, 0xde, 0x83, 0x5a, 0x18, 0x1a, 0x02, 0x53, 0xd3, 0x9c, 0x47, 0x92, 0xd9, 0x2b, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0x11, 0x38, 0xd2, 0xe0, 0x02, 0x00, 0x00,
}
