// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play_download.proto

package libplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Install struct {
	AndroidId                 *uint64  `protobuf:"fixed64,1,opt,name=androidId" json:"androidId,omitempty"`
	Version                   *int32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Bundled                   *bool    `protobuf:"varint,3,opt,name=bundled" json:"bundled,omitempty"`
	Pending                   *bool    `protobuf:"varint,4,opt,name=pending" json:"pending,omitempty"`
	LastUpdateTimestampMillis *int64   `protobuf:"varint,5,opt,name=lastUpdateTimestampMillis" json:"lastUpdateTimestampMillis,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Install) Reset()         { *m = Install{} }
func (m *Install) String() string { return proto.CompactTextString(m) }
func (*Install) ProtoMessage()    {}
func (*Install) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{0}
}

func (m *Install) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install.Unmarshal(m, b)
}
func (m *Install) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install.Marshal(b, m, deterministic)
}
func (m *Install) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install.Merge(m, src)
}
func (m *Install) XXX_Size() int {
	return xxx_messageInfo_Install.Size(m)
}
func (m *Install) XXX_DiscardUnknown() {
	xxx_messageInfo_Install.DiscardUnknown(m)
}

var xxx_messageInfo_Install proto.InternalMessageInfo

func (m *Install) GetAndroidId() uint64 {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return 0
}

func (m *Install) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Install) GetBundled() bool {
	if m != nil && m.Bundled != nil {
		return *m.Bundled
	}
	return false
}

func (m *Install) GetPending() bool {
	if m != nil && m.Pending != nil {
		return *m.Pending
	}
	return false
}

func (m *Install) GetLastUpdateTimestampMillis() int64 {
	if m != nil && m.LastUpdateTimestampMillis != nil {
		return *m.LastUpdateTimestampMillis
	}
	return 0
}

type Dependency struct {
	PackageName          *string  `protobuf:"bytes,1,opt,name=packageName" json:"packageName,omitempty"`
	MinVersionCode       *int32   `protobuf:"varint,2,opt,name=minVersionCode" json:"minVersionCode,omitempty"`
	VersionCodeMask      *int32   `protobuf:"varint,3,opt,name=versionCodeMask" json:"versionCodeMask,omitempty"`
	SkipPermissions      *bool    `protobuf:"varint,4,opt,name=skipPermissions" json:"skipPermissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{1}
}

func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetPackageName() string {
	if m != nil && m.PackageName != nil {
		return *m.PackageName
	}
	return ""
}

func (m *Dependency) GetMinVersionCode() int32 {
	if m != nil && m.MinVersionCode != nil {
		return *m.MinVersionCode
	}
	return 0
}

func (m *Dependency) GetVersionCodeMask() int32 {
	if m != nil && m.VersionCodeMask != nil {
		return *m.VersionCodeMask
	}
	return 0
}

func (m *Dependency) GetSkipPermissions() bool {
	if m != nil && m.SkipPermissions != nil {
		return *m.SkipPermissions
	}
	return false
}

type InstallDetails struct {
	InstallLocation      *int32        `protobuf:"varint,1,opt,name=installLocation" json:"installLocation,omitempty"`
	Size                 *int64        `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Dependency           []*Dependency `protobuf:"bytes,3,rep,name=dependency" json:"dependency,omitempty"`
	TargetSdkVersion     *int32        `protobuf:"varint,4,opt,name=targetSdkVersion" json:"targetSdkVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InstallDetails) Reset()         { *m = InstallDetails{} }
func (m *InstallDetails) String() string { return proto.CompactTextString(m) }
func (*InstallDetails) ProtoMessage()    {}
func (*InstallDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{2}
}

func (m *InstallDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallDetails.Unmarshal(m, b)
}
func (m *InstallDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallDetails.Marshal(b, m, deterministic)
}
func (m *InstallDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallDetails.Merge(m, src)
}
func (m *InstallDetails) XXX_Size() int {
	return xxx_messageInfo_InstallDetails.Size(m)
}
func (m *InstallDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallDetails.DiscardUnknown(m)
}

var xxx_messageInfo_InstallDetails proto.InternalMessageInfo

func (m *InstallDetails) GetInstallLocation() int32 {
	if m != nil && m.InstallLocation != nil {
		return *m.InstallLocation
	}
	return 0
}

func (m *InstallDetails) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *InstallDetails) GetDependency() []*Dependency {
	if m != nil {
		return m.Dependency
	}
	return nil
}

func (m *InstallDetails) GetTargetSdkVersion() int32 {
	if m != nil && m.TargetSdkVersion != nil {
		return *m.TargetSdkVersion
	}
	return 0
}

type PatchDetails struct {
	BaseVersionCode      *int32   `protobuf:"varint,1,opt,name=baseVersionCode" json:"baseVersionCode,omitempty"`
	Size                 *int64   `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchDetails) Reset()         { *m = PatchDetails{} }
func (m *PatchDetails) String() string { return proto.CompactTextString(m) }
func (*PatchDetails) ProtoMessage()    {}
func (*PatchDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{3}
}

func (m *PatchDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchDetails.Unmarshal(m, b)
}
func (m *PatchDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchDetails.Marshal(b, m, deterministic)
}
func (m *PatchDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchDetails.Merge(m, src)
}
func (m *PatchDetails) XXX_Size() int {
	return xxx_messageInfo_PatchDetails.Size(m)
}
func (m *PatchDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchDetails.DiscardUnknown(m)
}

var xxx_messageInfo_PatchDetails proto.InternalMessageInfo

func (m *PatchDetails) GetBaseVersionCode() int32 {
	if m != nil && m.BaseVersionCode != nil {
		return *m.BaseVersionCode
	}
	return 0
}

func (m *PatchDetails) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type FileMetadata struct {
	FileType             *int32          `protobuf:"varint,1,opt,name=fileType" json:"fileType,omitempty"`
	VersionCode          *int32          `protobuf:"varint,2,opt,name=versionCode" json:"versionCode,omitempty"`
	Size                 *int64          `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	SplitId              *string         `protobuf:"bytes,4,opt,name=splitId" json:"splitId,omitempty"`
	CompressedSize       *int64          `protobuf:"varint,5,opt,name=compressedSize" json:"compressedSize,omitempty"`
	PatchDetails         []*PatchDetails `protobuf:"bytes,6,rep,name=patchDetails" json:"patchDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FileMetadata) Reset()         { *m = FileMetadata{} }
func (m *FileMetadata) String() string { return proto.CompactTextString(m) }
func (*FileMetadata) ProtoMessage()    {}
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{4}
}

func (m *FileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata.Unmarshal(m, b)
}
func (m *FileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata.Marshal(b, m, deterministic)
}
func (m *FileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata.Merge(m, src)
}
func (m *FileMetadata) XXX_Size() int {
	return xxx_messageInfo_FileMetadata.Size(m)
}
func (m *FileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata proto.InternalMessageInfo

func (m *FileMetadata) GetFileType() int32 {
	if m != nil && m.FileType != nil {
		return *m.FileType
	}
	return 0
}

func (m *FileMetadata) GetVersionCode() int32 {
	if m != nil && m.VersionCode != nil {
		return *m.VersionCode
	}
	return 0
}

func (m *FileMetadata) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *FileMetadata) GetSplitId() string {
	if m != nil && m.SplitId != nil {
		return *m.SplitId
	}
	return ""
}

func (m *FileMetadata) GetCompressedSize() int64 {
	if m != nil && m.CompressedSize != nil {
		return *m.CompressedSize
	}
	return 0
}

func (m *FileMetadata) GetPatchDetails() []*PatchDetails {
	if m != nil {
		return m.PatchDetails
	}
	return nil
}

type AndroidAppPatchData struct {
	BaseVersionCode      *int32   `protobuf:"varint,1,opt,name=baseVersionCode" json:"baseVersionCode,omitempty"`
	BaseSignature        *string  `protobuf:"bytes,2,opt,name=baseSignature" json:"baseSignature,omitempty"`
	DownloadUrl          *string  `protobuf:"bytes,3,opt,name=downloadUrl" json:"downloadUrl,omitempty"`
	PatchFormat          *int32   `protobuf:"varint,4,opt,name=patchFormat" json:"patchFormat,omitempty"`
	MaxPatchSize         *int64   `protobuf:"varint,5,opt,name=maxPatchSize" json:"maxPatchSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndroidAppPatchData) Reset()         { *m = AndroidAppPatchData{} }
func (m *AndroidAppPatchData) String() string { return proto.CompactTextString(m) }
func (*AndroidAppPatchData) ProtoMessage()    {}
func (*AndroidAppPatchData) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{5}
}

func (m *AndroidAppPatchData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidAppPatchData.Unmarshal(m, b)
}
func (m *AndroidAppPatchData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidAppPatchData.Marshal(b, m, deterministic)
}
func (m *AndroidAppPatchData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidAppPatchData.Merge(m, src)
}
func (m *AndroidAppPatchData) XXX_Size() int {
	return xxx_messageInfo_AndroidAppPatchData.Size(m)
}
func (m *AndroidAppPatchData) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidAppPatchData.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidAppPatchData proto.InternalMessageInfo

func (m *AndroidAppPatchData) GetBaseVersionCode() int32 {
	if m != nil && m.BaseVersionCode != nil {
		return *m.BaseVersionCode
	}
	return 0
}

func (m *AndroidAppPatchData) GetBaseSignature() string {
	if m != nil && m.BaseSignature != nil {
		return *m.BaseSignature
	}
	return ""
}

func (m *AndroidAppPatchData) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *AndroidAppPatchData) GetPatchFormat() int32 {
	if m != nil && m.PatchFormat != nil {
		return *m.PatchFormat
	}
	return 0
}

func (m *AndroidAppPatchData) GetMaxPatchSize() int64 {
	if m != nil && m.MaxPatchSize != nil {
		return *m.MaxPatchSize
	}
	return 0
}

type AppFileMetadata struct {
	FileType              *int32               `protobuf:"varint,1,opt,name=fileType" json:"fileType,omitempty"`
	VersionCode           *int32               `protobuf:"varint,2,opt,name=versionCode" json:"versionCode,omitempty"`
	Size                  *int64               `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	DownloadUrl           *string              `protobuf:"bytes,4,opt,name=downloadUrl" json:"downloadUrl,omitempty"`
	PatchData             *AndroidAppPatchData `protobuf:"bytes,5,opt,name=patchData" json:"patchData,omitempty"`
	CompressedSize        *int64               `protobuf:"varint,6,opt,name=compressedSize" json:"compressedSize,omitempty"`
	CompressedDownloadUrl *string              `protobuf:"bytes,7,opt,name=compressedDownloadUrl" json:"compressedDownloadUrl,omitempty"`
	Signature             *string              `protobuf:"bytes,8,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *AppFileMetadata) Reset()         { *m = AppFileMetadata{} }
func (m *AppFileMetadata) String() string { return proto.CompactTextString(m) }
func (*AppFileMetadata) ProtoMessage()    {}
func (*AppFileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{6}
}

func (m *AppFileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppFileMetadata.Unmarshal(m, b)
}
func (m *AppFileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppFileMetadata.Marshal(b, m, deterministic)
}
func (m *AppFileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppFileMetadata.Merge(m, src)
}
func (m *AppFileMetadata) XXX_Size() int {
	return xxx_messageInfo_AppFileMetadata.Size(m)
}
func (m *AppFileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AppFileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AppFileMetadata proto.InternalMessageInfo

func (m *AppFileMetadata) GetFileType() int32 {
	if m != nil && m.FileType != nil {
		return *m.FileType
	}
	return 0
}

func (m *AppFileMetadata) GetVersionCode() int32 {
	if m != nil && m.VersionCode != nil {
		return *m.VersionCode
	}
	return 0
}

func (m *AppFileMetadata) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *AppFileMetadata) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *AppFileMetadata) GetPatchData() *AndroidAppPatchData {
	if m != nil {
		return m.PatchData
	}
	return nil
}

func (m *AppFileMetadata) GetCompressedSize() int64 {
	if m != nil && m.CompressedSize != nil {
		return *m.CompressedSize
	}
	return 0
}

func (m *AppFileMetadata) GetCompressedDownloadUrl() string {
	if m != nil && m.CompressedDownloadUrl != nil {
		return *m.CompressedDownloadUrl
	}
	return ""
}

func (m *AppFileMetadata) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

type EncryptionParams struct {
	Version              *int32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	EncryptionKey        *string  `protobuf:"bytes,2,opt,name=encryptionKey" json:"encryptionKey,omitempty"`
	HmacKey              *string  `protobuf:"bytes,3,opt,name=hmacKey" json:"hmacKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptionParams) Reset()         { *m = EncryptionParams{} }
func (m *EncryptionParams) String() string { return proto.CompactTextString(m) }
func (*EncryptionParams) ProtoMessage()    {}
func (*EncryptionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{7}
}

func (m *EncryptionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptionParams.Unmarshal(m, b)
}
func (m *EncryptionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptionParams.Marshal(b, m, deterministic)
}
func (m *EncryptionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptionParams.Merge(m, src)
}
func (m *EncryptionParams) XXX_Size() int {
	return xxx_messageInfo_EncryptionParams.Size(m)
}
func (m *EncryptionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptionParams.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptionParams proto.InternalMessageInfo

func (m *EncryptionParams) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *EncryptionParams) GetEncryptionKey() string {
	if m != nil && m.EncryptionKey != nil {
		return *m.EncryptionKey
	}
	return ""
}

func (m *EncryptionParams) GetHmacKey() string {
	if m != nil && m.HmacKey != nil {
		return *m.HmacKey
	}
	return ""
}

type SplitDeliveryData struct {
	Id                   *string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DownloadSize         *int64               `protobuf:"varint,2,opt,name=downloadSize" json:"downloadSize,omitempty"`
	GzippedDownloadSize  *int64               `protobuf:"varint,3,opt,name=gzippedDownloadSize" json:"gzippedDownloadSize,omitempty"`
	Signature            *string              `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	DownloadUrl          *string              `protobuf:"bytes,5,opt,name=downloadUrl" json:"downloadUrl,omitempty"`
	GzippedDownloadUrl   *string              `protobuf:"bytes,6,opt,name=gzippedDownloadUrl" json:"gzippedDownloadUrl,omitempty"`
	PatchData            *AndroidAppPatchData `protobuf:"bytes,7,opt,name=patchData" json:"patchData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SplitDeliveryData) Reset()         { *m = SplitDeliveryData{} }
func (m *SplitDeliveryData) String() string { return proto.CompactTextString(m) }
func (*SplitDeliveryData) ProtoMessage()    {}
func (*SplitDeliveryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{8}
}

func (m *SplitDeliveryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitDeliveryData.Unmarshal(m, b)
}
func (m *SplitDeliveryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitDeliveryData.Marshal(b, m, deterministic)
}
func (m *SplitDeliveryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitDeliveryData.Merge(m, src)
}
func (m *SplitDeliveryData) XXX_Size() int {
	return xxx_messageInfo_SplitDeliveryData.Size(m)
}
func (m *SplitDeliveryData) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitDeliveryData.DiscardUnknown(m)
}

var xxx_messageInfo_SplitDeliveryData proto.InternalMessageInfo

func (m *SplitDeliveryData) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *SplitDeliveryData) GetDownloadSize() int64 {
	if m != nil && m.DownloadSize != nil {
		return *m.DownloadSize
	}
	return 0
}

func (m *SplitDeliveryData) GetGzippedDownloadSize() int64 {
	if m != nil && m.GzippedDownloadSize != nil {
		return *m.GzippedDownloadSize
	}
	return 0
}

func (m *SplitDeliveryData) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *SplitDeliveryData) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *SplitDeliveryData) GetGzippedDownloadUrl() string {
	if m != nil && m.GzippedDownloadUrl != nil {
		return *m.GzippedDownloadUrl
	}
	return ""
}

func (m *SplitDeliveryData) GetPatchData() *AndroidAppPatchData {
	if m != nil {
		return m.PatchData
	}
	return nil
}

type AndroidAppDeliveryData struct {
	DownloadSize                  *int64               `protobuf:"varint,1,opt,name=downloadSize" json:"downloadSize,omitempty"`
	Signature                     *string              `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	DownloadUrl                   *string              `protobuf:"bytes,3,opt,name=downloadUrl" json:"downloadUrl,omitempty"`
	AdditionalFile                []*AppFileMetadata   `protobuf:"bytes,4,rep,name=additionalFile" json:"additionalFile,omitempty"`
	DownloadAuthCookie            []*HttpCookie        `protobuf:"bytes,5,rep,name=downloadAuthCookie" json:"downloadAuthCookie,omitempty"`
	ForwardLocked                 *bool                `protobuf:"varint,6,opt,name=forwardLocked" json:"forwardLocked,omitempty"`
	RefundTimeout                 *int64               `protobuf:"varint,7,opt,name=refundTimeout" json:"refundTimeout,omitempty"`
	ServerInitiated               *bool                `protobuf:"varint,8,opt,name=serverInitiated" json:"serverInitiated,omitempty"`
	PostInstallRefundWindowMillis *int64               `protobuf:"varint,9,opt,name=postInstallRefundWindowMillis" json:"postInstallRefundWindowMillis,omitempty"`
	ImmediateStartNeeded          *bool                `protobuf:"varint,10,opt,name=immediateStartNeeded" json:"immediateStartNeeded,omitempty"`
	PatchData                     *AndroidAppPatchData `protobuf:"bytes,11,opt,name=patchData" json:"patchData,omitempty"`
	EncryptionParams              *EncryptionParams    `protobuf:"bytes,12,opt,name=encryptionParams" json:"encryptionParams,omitempty"`
	GzippedDownloadUrl            *string              `protobuf:"bytes,13,opt,name=gzippedDownloadUrl" json:"gzippedDownloadUrl,omitempty"`
	GzippedDownloadSize           *int64               `protobuf:"varint,14,opt,name=gzippedDownloadSize" json:"gzippedDownloadSize,omitempty"`
	SplitDeliveryData             []*SplitDeliveryData `protobuf:"bytes,15,rep,name=splitDeliveryData" json:"splitDeliveryData,omitempty"`
	InstallLocation               *int32               `protobuf:"varint,16,opt,name=installLocation" json:"installLocation,omitempty"`
	EverExternallyHosted          *bool                `protobuf:"varint,17,opt,name=everExternallyHosted" json:"everExternallyHosted,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}             `json:"-"`
	XXX_unrecognized              []byte               `json:"-"`
	XXX_sizecache                 int32                `json:"-"`
}

func (m *AndroidAppDeliveryData) Reset()         { *m = AndroidAppDeliveryData{} }
func (m *AndroidAppDeliveryData) String() string { return proto.CompactTextString(m) }
func (*AndroidAppDeliveryData) ProtoMessage()    {}
func (*AndroidAppDeliveryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{9}
}

func (m *AndroidAppDeliveryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndroidAppDeliveryData.Unmarshal(m, b)
}
func (m *AndroidAppDeliveryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndroidAppDeliveryData.Marshal(b, m, deterministic)
}
func (m *AndroidAppDeliveryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndroidAppDeliveryData.Merge(m, src)
}
func (m *AndroidAppDeliveryData) XXX_Size() int {
	return xxx_messageInfo_AndroidAppDeliveryData.Size(m)
}
func (m *AndroidAppDeliveryData) XXX_DiscardUnknown() {
	xxx_messageInfo_AndroidAppDeliveryData.DiscardUnknown(m)
}

var xxx_messageInfo_AndroidAppDeliveryData proto.InternalMessageInfo

func (m *AndroidAppDeliveryData) GetDownloadSize() int64 {
	if m != nil && m.DownloadSize != nil {
		return *m.DownloadSize
	}
	return 0
}

func (m *AndroidAppDeliveryData) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *AndroidAppDeliveryData) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *AndroidAppDeliveryData) GetAdditionalFile() []*AppFileMetadata {
	if m != nil {
		return m.AdditionalFile
	}
	return nil
}

func (m *AndroidAppDeliveryData) GetDownloadAuthCookie() []*HttpCookie {
	if m != nil {
		return m.DownloadAuthCookie
	}
	return nil
}

func (m *AndroidAppDeliveryData) GetForwardLocked() bool {
	if m != nil && m.ForwardLocked != nil {
		return *m.ForwardLocked
	}
	return false
}

func (m *AndroidAppDeliveryData) GetRefundTimeout() int64 {
	if m != nil && m.RefundTimeout != nil {
		return *m.RefundTimeout
	}
	return 0
}

func (m *AndroidAppDeliveryData) GetServerInitiated() bool {
	if m != nil && m.ServerInitiated != nil {
		return *m.ServerInitiated
	}
	return false
}

func (m *AndroidAppDeliveryData) GetPostInstallRefundWindowMillis() int64 {
	if m != nil && m.PostInstallRefundWindowMillis != nil {
		return *m.PostInstallRefundWindowMillis
	}
	return 0
}

func (m *AndroidAppDeliveryData) GetImmediateStartNeeded() bool {
	if m != nil && m.ImmediateStartNeeded != nil {
		return *m.ImmediateStartNeeded
	}
	return false
}

func (m *AndroidAppDeliveryData) GetPatchData() *AndroidAppPatchData {
	if m != nil {
		return m.PatchData
	}
	return nil
}

func (m *AndroidAppDeliveryData) GetEncryptionParams() *EncryptionParams {
	if m != nil {
		return m.EncryptionParams
	}
	return nil
}

func (m *AndroidAppDeliveryData) GetGzippedDownloadUrl() string {
	if m != nil && m.GzippedDownloadUrl != nil {
		return *m.GzippedDownloadUrl
	}
	return ""
}

func (m *AndroidAppDeliveryData) GetGzippedDownloadSize() int64 {
	if m != nil && m.GzippedDownloadSize != nil {
		return *m.GzippedDownloadSize
	}
	return 0
}

func (m *AndroidAppDeliveryData) GetSplitDeliveryData() []*SplitDeliveryData {
	if m != nil {
		return m.SplitDeliveryData
	}
	return nil
}

func (m *AndroidAppDeliveryData) GetInstallLocation() int32 {
	if m != nil && m.InstallLocation != nil {
		return *m.InstallLocation
	}
	return 0
}

func (m *AndroidAppDeliveryData) GetEverExternallyHosted() bool {
	if m != nil && m.EverExternallyHosted != nil {
		return *m.EverExternallyHosted
	}
	return false
}

type DeliveryResponse struct {
	Status               *int32                  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	AppDeliveryData      *AndroidAppDeliveryData `protobuf:"bytes,2,opt,name=appDeliveryData" json:"appDeliveryData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DeliveryResponse) Reset()         { *m = DeliveryResponse{} }
func (m *DeliveryResponse) String() string { return proto.CompactTextString(m) }
func (*DeliveryResponse) ProtoMessage()    {}
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d54949c0efcf52, []int{10}
}

func (m *DeliveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryResponse.Unmarshal(m, b)
}
func (m *DeliveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryResponse.Marshal(b, m, deterministic)
}
func (m *DeliveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryResponse.Merge(m, src)
}
func (m *DeliveryResponse) XXX_Size() int {
	return xxx_messageInfo_DeliveryResponse.Size(m)
}
func (m *DeliveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryResponse proto.InternalMessageInfo

func (m *DeliveryResponse) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *DeliveryResponse) GetAppDeliveryData() *AndroidAppDeliveryData {
	if m != nil {
		return m.AppDeliveryData
	}
	return nil
}

func init() {
	proto.RegisterType((*Install)(nil), "playapi.proto.finsky.download.Install")
	proto.RegisterType((*Dependency)(nil), "playapi.proto.finsky.download.Dependency")
	proto.RegisterType((*InstallDetails)(nil), "playapi.proto.finsky.download.InstallDetails")
	proto.RegisterType((*PatchDetails)(nil), "playapi.proto.finsky.download.PatchDetails")
	proto.RegisterType((*FileMetadata)(nil), "playapi.proto.finsky.download.FileMetadata")
	proto.RegisterType((*AndroidAppPatchData)(nil), "playapi.proto.finsky.download.AndroidAppPatchData")
	proto.RegisterType((*AppFileMetadata)(nil), "playapi.proto.finsky.download.AppFileMetadata")
	proto.RegisterType((*EncryptionParams)(nil), "playapi.proto.finsky.download.EncryptionParams")
	proto.RegisterType((*SplitDeliveryData)(nil), "playapi.proto.finsky.download.SplitDeliveryData")
	proto.RegisterType((*AndroidAppDeliveryData)(nil), "playapi.proto.finsky.download.AndroidAppDeliveryData")
	proto.RegisterType((*DeliveryResponse)(nil), "playapi.proto.finsky.download.DeliveryResponse")
}

func init() { proto.RegisterFile("play_download.proto", fileDescriptor_48d54949c0efcf52) }

var fileDescriptor_48d54949c0efcf52 = []byte{
	// 1051 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x86, 0xec, 0x24, 0x8e, 0x4f, 0xfe, 0x99, 0xae, 0xd0, 0x8a, 0x15, 0xf3, 0x84, 0x62, 0xf0,
	0x36, 0xc0, 0x29, 0x8c, 0xed, 0x6e, 0x37, 0x59, 0xdd, 0xa2, 0xd9, 0x92, 0x2e, 0xa0, 0xdb, 0x0e,
	0xd8, 0x80, 0x15, 0x8c, 0xc8, 0xd8, 0x84, 0x25, 0x91, 0x20, 0x69, 0xa7, 0xee, 0x2b, 0xec, 0x4d,
	0x76, 0xbb, 0xcb, 0x5d, 0xef, 0x72, 0x57, 0x7b, 0x86, 0x3d, 0xc1, 0x5e, 0x60, 0x20, 0x25, 0xc5,
	0x92, 0x2c, 0xd7, 0xbd, 0x68, 0xef, 0xcc, 0xef, 0x1c, 0x1e, 0x9e, 0xef, 0x3b, 0x3f, 0x32, 0x1c,
	0xcb, 0x88, 0xcc, 0x5f, 0x51, 0x71, 0x93, 0x44, 0x82, 0xd0, 0x9e, 0x54, 0xc2, 0x08, 0x74, 0xdf,
	0x82, 0x44, 0xf2, 0xf4, 0xd8, 0xbb, 0xe6, 0x89, 0x9e, 0xcc, 0x7b, 0xb9, 0xd3, 0xbd, 0x23, 0x77,
	0x27, 0x14, 0x71, 0x2c, 0x92, 0xd4, 0x25, 0xf8, 0xc3, 0x83, 0xd6, 0x59, 0xa2, 0x0d, 0x89, 0x22,
	0xf4, 0x09, 0xb4, 0x49, 0x42, 0x95, 0xe0, 0xf4, 0x8c, 0xfa, 0x5e, 0xc7, 0xeb, 0x6e, 0xe1, 0x05,
	0x80, 0x7c, 0x68, 0xcd, 0x98, 0xd2, 0x5c, 0x24, 0x7e, 0xa3, 0xe3, 0x75, 0x37, 0x71, 0x7e, 0xb4,
	0x96, 0xab, 0x69, 0x42, 0x23, 0x46, 0xfd, 0x66, 0xc7, 0xeb, 0x6e, 0xe3, 0xfc, 0x68, 0x2d, 0x92,
	0x25, 0x94, 0x27, 0x23, 0x7f, 0x23, 0xb5, 0x64, 0x47, 0xf4, 0x2d, 0x7c, 0x1c, 0x11, 0x6d, 0x5e,
	0x48, 0x4a, 0x0c, 0x7b, 0xce, 0x63, 0xa6, 0x0d, 0x89, 0xe5, 0x05, 0x8f, 0x22, 0xae, 0xfd, 0xcd,
	0x8e, 0xd7, 0x6d, 0xe2, 0xd5, 0x0e, 0xc1, 0xef, 0x1e, 0xc0, 0x80, 0xd9, 0x58, 0x2c, 0x09, 0xe7,
	0xa8, 0x03, 0x3b, 0x92, 0x84, 0x13, 0x32, 0x62, 0xcf, 0x48, 0xcc, 0x5c, 0xea, 0x6d, 0x5c, 0x84,
	0xd0, 0xe7, 0xb0, 0x1f, 0xf3, 0xe4, 0x65, 0x9a, 0xf0, 0x23, 0x41, 0x59, 0xc6, 0xa1, 0x82, 0xa2,
	0x2e, 0x1c, 0xcc, 0x16, 0xc7, 0x0b, 0xa2, 0x27, 0x8e, 0xd2, 0x26, 0xae, 0xc2, 0xd6, 0x53, 0x4f,
	0xb8, 0xbc, 0x64, 0x2a, 0xe6, 0xda, 0x5a, 0x74, 0x46, 0xb1, 0x0a, 0x07, 0x7f, 0x79, 0xb0, 0x9f,
	0x49, 0x3c, 0x60, 0x86, 0xf0, 0x48, 0xdb, 0xcb, 0x3c, 0x45, 0xce, 0x45, 0x48, 0x8c, 0xd5, 0xd4,
	0x4b, 0x9f, 0xa9, 0xc0, 0x08, 0xc1, 0x86, 0xe6, 0x6f, 0xd2, 0x74, 0x9b, 0xd8, 0xfd, 0x46, 0x67,
	0x00, 0xf4, 0x96, 0xbc, 0xdf, 0xec, 0x34, 0xbb, 0x3b, 0xfd, 0x2f, 0x7a, 0x6f, 0x2d, 0x7d, 0x6f,
	0xa1, 0x16, 0x2e, 0x5c, 0x46, 0x5f, 0xc2, 0xa1, 0x21, 0x6a, 0xc4, 0xcc, 0x90, 0x4e, 0x32, 0x1d,
	0x1c, 0x8d, 0x4d, 0xbc, 0x84, 0x07, 0xe7, 0xb0, 0x7b, 0x49, 0x4c, 0x38, 0x2e, 0x90, 0xb8, 0x22,
	0x9a, 0x15, 0x45, 0xcd, 0x48, 0x54, 0xe0, 0x3a, 0x12, 0xc1, 0x7f, 0x1e, 0xec, 0x3e, 0xe1, 0x11,
	0xbb, 0x60, 0x86, 0x50, 0x62, 0x08, 0xba, 0x07, 0xdb, 0xd7, 0x3c, 0x62, 0xcf, 0xe7, 0x32, 0x8f,
	0x73, 0x7b, 0xb6, 0x05, 0x9e, 0x2d, 0xd5, 0xae, 0x08, 0xdd, 0x3e, 0xd1, 0x2c, 0xe8, 0xe4, 0x43,
	0x4b, 0xcb, 0x88, 0x9b, 0x33, 0xea, 0x38, 0xb5, 0x71, 0x7e, 0xb4, 0xed, 0x10, 0x8a, 0x58, 0x2a,
	0xa6, 0x35, 0xa3, 0x43, 0x7b, 0x2f, 0x6d, 0xb9, 0x0a, 0x8a, 0x7e, 0x84, 0x5d, 0x59, 0xa0, 0xec,
	0x6f, 0x39, 0xad, 0xbf, 0x5a, 0xa3, 0x75, 0x51, 0x25, 0x5c, 0x0a, 0x10, 0xfc, 0xed, 0xc1, 0xf1,
	0x69, 0x3a, 0x52, 0xa7, 0x52, 0xa6, 0x8e, 0x96, 0xfc, 0xbb, 0x6b, 0xf9, 0x00, 0xf6, 0x2c, 0x34,
	0xe4, 0xa3, 0x84, 0x98, 0xa9, 0x4a, 0xc5, 0x68, 0xe3, 0x32, 0x68, 0x05, 0xcb, 0xd3, 0x79, 0xa1,
	0x22, 0xa7, 0x4a, 0x1b, 0x17, 0xa1, 0x74, 0x66, 0x4c, 0x38, 0x7e, 0x22, 0x54, 0x4c, 0x4c, 0x56,
	0xf4, 0x22, 0x84, 0x02, 0xd8, 0x8d, 0xc9, 0x6b, 0x97, 0x63, 0x41, 0xa2, 0x12, 0x16, 0xfc, 0xd3,
	0x80, 0x83, 0x53, 0x29, 0x3f, 0x70, 0x21, 0x2b, 0x6c, 0x36, 0x96, 0xd9, 0x5c, 0x42, 0x5b, 0xe6,
	0x62, 0xba, 0x44, 0x77, 0xfa, 0xfd, 0x35, 0x55, 0xaa, 0x29, 0x03, 0x5e, 0x04, 0xa9, 0x69, 0x91,
	0xad, 0xda, 0x16, 0xf9, 0x1a, 0x3e, 0x5a, 0x20, 0x83, 0x42, 0x96, 0x2d, 0x97, 0x65, 0xbd, 0xd1,
	0xae, 0x5a, 0x7d, 0x5b, 0xc1, 0x6d, 0xe7, 0xb9, 0x00, 0x82, 0x08, 0x0e, 0x1f, 0x27, 0xa1, 0x9a,
	0x4b, 0xbb, 0x02, 0x2e, 0x89, 0x22, 0xb1, 0x2e, 0xae, 0x5f, 0xaf, 0xbc, 0x7e, 0x1f, 0xc0, 0x1e,
	0xbb, 0xf5, 0xfe, 0x81, 0xcd, 0xf3, 0x8e, 0x28, 0x81, 0xf6, 0xfe, 0x38, 0x26, 0xa1, 0xb5, 0xa7,
	0xdd, 0x90, 0x1f, 0x83, 0x3f, 0x1b, 0x70, 0x34, 0xb4, 0x83, 0x31, 0x60, 0x11, 0x9f, 0x31, 0x35,
	0x77, 0xfc, 0xf7, 0xa1, 0xc1, 0x69, 0xb6, 0x4a, 0x1b, 0x9c, 0xda, 0x6e, 0xc8, 0xa5, 0x1b, 0x2e,
	0x66, 0xb9, 0x84, 0xa1, 0x87, 0x70, 0x3c, 0x7a, 0xc3, 0xa5, 0x5c, 0x70, 0x1d, 0x2e, 0x4a, 0x59,
	0x67, 0x2a, 0xeb, 0xb0, 0x51, 0xd1, 0xa1, 0x5a, 0xf7, 0xcd, 0xe5, 0xba, 0xf7, 0x00, 0x55, 0xc2,
	0x5a, 0xc7, 0x2d, 0xe7, 0x58, 0x63, 0x29, 0xf7, 0x49, 0xeb, 0x3d, 0xf4, 0x49, 0xf0, 0x6f, 0x0b,
	0xee, 0x2e, 0x5c, 0x4a, 0x12, 0x56, 0x25, 0xf3, 0x6a, 0x24, 0x2b, 0x09, 0xd0, 0x58, 0x23, 0x40,
	0xcd, 0x18, 0xbf, 0x84, 0x7d, 0x42, 0x29, 0xb7, 0x55, 0x26, 0x91, 0x1d, 0x43, 0x7f, 0xc3, 0xed,
	0xa8, 0xde, 0x3a, 0x56, 0xe5, 0xa1, 0xc5, 0x95, 0x28, 0xe8, 0x12, 0x50, 0xee, 0x7b, 0x3a, 0x35,
	0xe3, 0x47, 0x42, 0x4c, 0xb8, 0x5d, 0x01, 0x36, 0x76, 0xa7, 0x3e, 0xf6, 0x53, 0x63, 0x64, 0xea,
	0x87, 0x6b, 0xee, 0xda, 0x36, 0xbd, 0x16, 0xea, 0x86, 0x28, 0x7a, 0x2e, 0xc2, 0x09, 0xa3, 0xae,
	0x4a, 0xdb, 0xb8, 0x0c, 0x5a, 0x2f, 0xc5, 0xae, 0xa7, 0x09, 0xb5, 0x9f, 0x7c, 0x31, 0x35, 0xae,
	0x48, 0x4d, 0x5c, 0x06, 0xdd, 0xc7, 0x97, 0xa9, 0x19, 0x53, 0x67, 0x09, 0x37, 0x9c, 0x18, 0x46,
	0xdd, 0x10, 0xd9, 0x8f, 0x6f, 0x19, 0x46, 0x03, 0xb8, 0x2f, 0x85, 0x36, 0xd9, 0xf7, 0x17, 0xbb,
	0x28, 0x3f, 0xf1, 0x84, 0x8a, 0x9b, 0xec, 0xbf, 0x46, 0xdb, 0xc5, 0x7f, 0xbb, 0x13, 0xea, 0xc3,
	0x1d, 0x1e, 0xc7, 0x8c, 0xda, 0x98, 0x43, 0x43, 0x94, 0x79, 0xc6, 0x18, 0x65, 0xd4, 0x07, 0xf7,
	0x68, 0xad, 0xad, 0xdc, 0x6a, 0x3b, 0xef, 0x63, 0x25, 0xfd, 0x02, 0x87, 0xac, 0xb2, 0x16, 0xfc,
	0x5d, 0x17, 0xf8, 0x64, 0x4d, 0xe0, 0xea, 0x36, 0xc1, 0x4b, 0x81, 0x56, 0x4c, 0xd2, 0xde, 0xca,
	0x49, 0x5a, 0x31, 0xeb, 0xfb, 0xab, 0x67, 0xfd, 0x57, 0x38, 0xd2, 0xd5, 0x35, 0xe3, 0x1f, 0xb8,
	0x8e, 0x7a, 0xb8, 0x26, 0xff, 0xa5, 0xf5, 0x84, 0x97, 0x43, 0xd5, 0xfd, 0xa9, 0x3a, 0xac, 0xff,
	0x53, 0xd5, 0x87, 0x3b, 0x6c, 0xc6, 0xd4, 0xe3, 0xd7, 0x86, 0xa9, 0x84, 0x44, 0xd1, 0xfc, 0xa9,
	0xd0, 0xb6, 0x87, 0x8e, 0xd2, 0x72, 0xd6, 0xd9, 0x82, 0xdf, 0x3c, 0x38, 0xcc, 0x9f, 0xc3, 0x4c,
	0x4b, 0x91, 0x68, 0x86, 0xee, 0xc2, 0x96, 0x36, 0xc4, 0x4c, 0x75, 0xb6, 0x93, 0xb3, 0x13, 0x7a,
	0x05, 0x07, 0xa4, 0xbc, 0x0c, 0xdc, 0x6c, 0xef, 0xf4, 0xbf, 0x79, 0xe7, 0x0e, 0x28, 0xb1, 0xad,
	0x46, 0xfb, 0xee, 0xb3, 0x9f, 0x3f, 0x1d, 0x71, 0x33, 0x9e, 0x5e, 0xf5, 0x42, 0x11, 0x9f, 0x7c,
	0x2f, 0xf4, 0x78, 0x4a, 0x06, 0x82, 0xe9, 0x93, 0x88, 0x5f, 0x29, 0x66, 0xdf, 0xf8, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x9b, 0x25, 0x9d, 0x21, 0x0c, 0x00, 0x00,
}
